import { ALL_PERMISSIONS, PERMISSIONS, type PermissionCode } from './codes.js';

/**
 * System role definitions, seeded once with `organizationId = null`.
 * Tenants never mutate these — they clone one into a custom org-scoped role.
 */

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_OWNER: 'ORG_OWNER',
  ORG_ADMIN: 'ORG_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
  LAB_ASSISTANT: 'LAB_ASSISTANT',
  LAB_MANAGER: 'LAB_MANAGER',
  PHARMACIST: 'PHARMACIST',
  ACCOUNTANT: 'ACCOUNTANT',
  PATIENT: 'PATIENT',
} as const;

export type SystemRoleCode = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export type RoleScopeLevel = 'PLATFORM' | 'ORGANIZATION' | 'BRANCH';

export interface SystemRoleDefinition {
  code: SystemRoleCode;
  name: string;
  description: string;
  scopeLevel: RoleScopeLevel;
  permissions: PermissionCode[];
}

const P = PERMISSIONS;

export const SYSTEM_ROLE_DEFINITIONS: SystemRoleDefinition[] = [
  {
    code: SYSTEM_ROLES.SUPER_ADMIN,
    name: 'Super Admin',
    description: 'Platform operator. Seeded directly into the database, never created via the UI.',
    scopeLevel: 'PLATFORM',
    permissions: ALL_PERMISSIONS,
  },
  {
    code: SYSTEM_ROLES.ORG_OWNER,
    name: 'Organization Owner',
    description: 'Registered the clinic. Full control including subscription and billing.',
    scopeLevel: 'ORGANIZATION',
    // Everything except platform-level permissions.
    permissions: ALL_PERMISSIONS.filter((p) => !p.startsWith('platform.')),
  },
  {
    code: SYSTEM_ROLES.ORG_ADMIN,
    name: 'Organization Admin',
    description: 'Manages every branch, but cannot change the subscription or delete the org.',
    scopeLevel: 'ORGANIZATION',
    permissions: ALL_PERMISSIONS.filter(
      (p) =>
        !p.startsWith('platform.') &&
        p !== P.ORG_BILLING_MANAGE &&
        p !== P.BRANCH_DELETE &&
        p !== P.PATIENT_DELETE
    ),
  },
  {
    code: SYSTEM_ROLES.BRANCH_ADMIN,
    name: 'Branch Admin',
    description:
      'Runs one or more branches. Which branches is decided per assignment in membership_roles, not here.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.BRANCH_READ,
      P.BRANCH_UPDATE,
      P.IAM_USER_READ,
      P.IAM_USER_INVITE,
      P.IAM_USER_UPDATE,
      P.IAM_ROLE_READ,
      P.PATIENT_READ,
      P.PATIENT_CREATE,
      P.PATIENT_UPDATE,
      P.PATIENT_MEDICAL_HISTORY_READ,
      P.PATIENT_DOCUMENT_READ,
      P.APPOINTMENT_READ,
      P.APPOINTMENT_CREATE,
      P.APPOINTMENT_UPDATE,
      P.APPOINTMENT_CANCEL,
      P.APPOINTMENT_CHECKIN,
      P.QUEUE_MANAGE,
      P.ENCOUNTER_READ,
      P.PRESCRIPTION_READ,
      P.LAB_ORDER_READ,
      P.LAB_MASTER_MANAGE,
      P.MEDICINE_READ,
      P.MEDICINE_MANAGE,
      P.DISPENSE_READ,
      P.SUPPLIER_MANAGE,
      P.PURCHASE_ORDER_READ,
      P.PURCHASE_ORDER_MANAGE,
      P.GOODS_RECEIPT_MANAGE,
      P.STOCK_READ,
      P.STOCK_ADJUST,
      P.STOCK_TRANSFER,
      P.BATCH_MANAGE,
      P.INVOICE_READ,
      P.INVOICE_CREATE,
      P.INVOICE_UPDATE,
      P.INVOICE_CANCEL,
      P.PAYMENT_COLLECT,
      P.CREDIT_NOTE_ISSUE,
      P.REFUND_PROCESS,
      P.DOCTOR_PAYOUT_MANAGE,
      P.REPORT_DASHBOARD,
      P.REPORT_REVENUE,
      P.REPORT_CLINICAL,
      P.REPORT_INVENTORY,
      P.REPORT_EXPORT,
      P.SETTINGS_BRANCH_READ,
      P.SETTINGS_BRANCH_WRITE,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.DOCTOR,
    name: 'Doctor',
    description: 'Consults patients. Scoped to the branches they practise at.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.PATIENT_CREATE,
      P.PATIENT_UPDATE,
      P.PATIENT_MEDICAL_HISTORY_READ,
      P.PATIENT_MEDICAL_HISTORY_WRITE,
      P.PATIENT_DOCUMENT_READ,
      P.PATIENT_DOCUMENT_UPLOAD,
      P.APPOINTMENT_READ,
      P.APPOINTMENT_CREATE,
      P.APPOINTMENT_UPDATE,
      P.APPOINTMENT_CANCEL,
      P.ENCOUNTER_READ,
      P.ENCOUNTER_CREATE,
      P.ENCOUNTER_CLOSE,
      P.VITALS_RECORD,
      P.PRESCRIPTION_READ,
      P.PRESCRIPTION_CREATE,
      P.PRESCRIPTION_SIGN,
      P.LAB_ORDER_READ,
      P.LAB_ORDER_CREATE,
      P.MEDICINE_READ,
      P.INVOICE_READ,
      P.REPORT_DASHBOARD,
      P.REPORT_CLINICAL,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.NURSE,
    name: 'Nurse',
    description: 'Records vitals, assists the encounter, manages the queue.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.PATIENT_UPDATE,
      P.PATIENT_MEDICAL_HISTORY_READ,
      P.APPOINTMENT_READ,
      P.APPOINTMENT_CHECKIN,
      P.QUEUE_MANAGE,
      P.ENCOUNTER_READ,
      P.VITALS_RECORD,
      P.PRESCRIPTION_READ,
      P.LAB_ORDER_READ,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.RECEPTIONIST,
    name: 'Receptionist / Front Desk',
    description: 'Registers patients, books appointments, collects payment. No clinical access.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.PATIENT_CREATE,
      P.PATIENT_UPDATE,
      P.APPOINTMENT_READ,
      P.APPOINTMENT_CREATE,
      P.APPOINTMENT_UPDATE,
      P.APPOINTMENT_CANCEL,
      P.APPOINTMENT_CHECKIN,
      P.QUEUE_MANAGE,
      P.INVOICE_READ,
      P.INVOICE_CREATE,
      P.PAYMENT_COLLECT,
      P.REPORT_DASHBOARD,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.LAB_ASSISTANT,
    name: 'Lab Assistant',
    description: 'Collects samples and enters results. Cannot verify or release a report.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.LAB_ORDER_READ,
      P.LAB_SAMPLE_COLLECT,
      P.LAB_RESULT_ENTER,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.LAB_MANAGER,
    name: 'Lab Manager',
    description: 'Verifies results and releases reports. Separation of duty from the assistant.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.LAB_ORDER_READ,
      P.LAB_ORDER_CREATE,
      P.LAB_SAMPLE_COLLECT,
      P.LAB_RESULT_ENTER,
      P.LAB_RESULT_VERIFY,
      P.LAB_REPORT_RELEASE,
      P.LAB_MASTER_MANAGE,
      P.INVOICE_READ,
      P.REPORT_DASHBOARD,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.PHARMACIST,
    name: 'Pharmacist',
    description: 'Dispenses against prescriptions and manages stock.',
    scopeLevel: 'BRANCH',
    permissions: [
      P.PATIENT_READ,
      P.PRESCRIPTION_READ,
      P.MEDICINE_READ,
      P.MEDICINE_MANAGE,
      P.DISPENSE_READ,
      P.DISPENSE_CREATE,
      P.DISPENSE_RETURN,
      P.SUPPLIER_MANAGE,
      P.PURCHASE_ORDER_READ,
      P.PURCHASE_ORDER_MANAGE,
      P.GOODS_RECEIPT_MANAGE,
      P.STOCK_READ,
      P.STOCK_ADJUST,
      P.STOCK_TRANSFER,
      P.BATCH_MANAGE,
      P.INVOICE_READ,
      P.INVOICE_CREATE,
      P.PAYMENT_COLLECT,
      P.REPORT_INVENTORY,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.ACCOUNTANT,
    name: 'Accountant',
    description: 'Billing and revenue. Reads patient identity only, never clinical notes.',
    scopeLevel: 'ORGANIZATION',
    permissions: [
      P.PATIENT_READ,
      P.APPOINTMENT_READ,
      P.INVOICE_READ,
      P.INVOICE_CREATE,
      P.INVOICE_UPDATE,
      P.INVOICE_CANCEL,
      P.PAYMENT_COLLECT,
      P.CREDIT_NOTE_ISSUE,
      P.REFUND_PROCESS,
      P.DOCTOR_PAYOUT_MANAGE,
      P.REPORT_DASHBOARD,
      P.REPORT_REVENUE,
      P.REPORT_EXPORT,
      P.ORG_BILLING_READ,
      P.SETTINGS_USER_WRITE,
    ],
  },
  {
    code: SYSTEM_ROLES.PATIENT,
    name: 'Patient',
    description:
      'Portal access to their own records only. Row filtering is by patient_id, not by this role.',
    scopeLevel: 'ORGANIZATION',
    permissions: [
      P.PATIENT_READ,
      P.APPOINTMENT_READ,
      P.APPOINTMENT_CREATE,
      P.APPOINTMENT_CANCEL,
      P.PRESCRIPTION_READ,
      P.LAB_ORDER_READ,
      P.INVOICE_READ,
      P.PATIENT_DOCUMENT_READ,
      P.SETTINGS_USER_WRITE,
    ],
  },
];
