#!/usr/bin/env node
/**
 * .kb generator — builds the symbol index from source.
 *
 * Everything under .kb/ except README.md and notes/ is generated by this file.
 * Do not hand-edit generated output; edit the source or this script.
 *
 *   node .kb/generate.mjs            regenerate
 *   node .kb/generate.mjs --check    exit 1 if output would change (CI/hooks)
 *   node .kb/generate.mjs --quiet    no stdout unless something changed
 *
 * No new dependency: `typescript` is already a root devDependency, and this
 * uses the syntax-only parser (no type checker, no Program) so a full rebuild
 * of the repo stays well under a second.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import ts from 'typescript';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const KB = join(ROOT, '.kb');
const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const QUIET = args.has('--quiet');

const SCAN_ROOTS = ['apps', 'packages'];
const SKIP_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  '.next',
  '.turbo',
  'generated',
  'coverage',
  '.git',
  'migrations',
  'public',
]);
const SOURCE_EXT = /\.(ts|tsx|mts|cts)$/;
const DECL_EXT = /\.d\.ts$/;

// ---------------------------------------------------------------------------
// file discovery
// ---------------------------------------------------------------------------

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.kb') {
      if (entry.isDirectory()) continue;
    }
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(full, out);
    } else if (SOURCE_EXT.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

const files = SCAN_ROOTS.flatMap((r) => (existsSync(join(ROOT, r)) ? walk(join(ROOT, r)) : []))
  .map((f) => relative(ROOT, f).split(sep).join('/'))
  .sort();

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

const clean = (s) =>
  String(s ?? '')
    .replace(/[\t\r\n]+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();
const truncate = (s, n) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
const isPascal = (n) => /^[A-Z][A-Za-z0-9]*$/.test(n);
const isHook = (n) => /^use[A-Z]/.test(n);
const isScreamingConst = (n) => /^[A-Z0-9_]+$/.test(n);

/** Module id: the directory a file lives in, minus the `src/` noise. */
function moduleIdOf(file) {
  const dir = file.split('/').slice(0, -1).join('/');
  return dir.replace(/\/src(\/|$)/, '/').replace(/\/$/, '') || dir;
}

const kbFileNameOf = (moduleId) =>
  `${moduleId
    .replace(/[/[\]()]/g, '.')
    .replace(/\.+/g, '.')
    .replace(/^\.|\.$/g, '')}.md`;

/**
 * JSDoc for a node, if it reads like a symbol doc rather than a file banner.
 * This codebase opens most files with a long explanatory block, and TS attaches
 * that block to whatever statement follows it. Length is the discriminator:
 * banners are paragraphs, symbol docs are a line or two.
 */
const BANNER_MIN = 200;

function docOf(node) {
  const docs = node.jsDoc;
  if (!docs?.length) return { summary: '', banner: '' };
  const last = docs[docs.length - 1];
  const text = clean(
    typeof last.comment === 'string'
      ? last.comment
      : (last.comment ?? []).map((c) => c.text).join(' ')
  );
  if (!text) return { summary: '', banner: '' };
  if (text.length >= BANNER_MIN) return { summary: '', banner: text };
  return { summary: text, banner: '' };
}

function firstSentence(text) {
  const m = text.match(/^(.+?[.!?])(\s|$)/);
  return clean(m ? m[1] : text);
}

// ---------------------------------------------------------------------------
// per-file extraction
// ---------------------------------------------------------------------------

const symbols = []; // flat symbol rows
const moduleMeta = new Map(); // moduleId -> { files:Set, banner:string }
const routes = []; // express route rows
const barrels = []; // re-export edges
const fileBanners = new Map(); // file -> its opening explanatory block
const importedContracts = new Map(); // file -> Set of names pulled from @rcln/contracts
const importGraph = new Map(); // file -> Set of workspace packages it imports

function recordModule(moduleId, file, banner) {
  let m = moduleMeta.get(moduleId);
  if (!m) {
    m = { files: new Set(), banner: '' };
    moduleMeta.set(moduleId, m);
  }
  m.files.add(file);
  if (banner && !m.banner) m.banner = banner;
}

function sigOfFunctionLike(node, src) {
  const params = node.parameters
    .map((p) => {
      const name = p.name.getText(src);
      const type = p.type ? `: ${clean(p.type.getText(src))}` : '';
      const opt = p.questionToken ? '?' : '';
      return truncate(clean(`${name}${opt}${type}`), 60);
    })
    .join(', ');
  const ret = node.type ? `: ${truncate(clean(node.type.getText(src)), 60)}` : '';
  return truncate(`(${params})${ret}`, 200);
}

function constPreview(init, src) {
  if (!init) return '';
  if (ts.isStringLiteralLike(init) || ts.isNumericLiteral(init))
    return truncate(clean(init.getText(src)), 60);
  if (init.kind === ts.SyntaxKind.TrueKeyword || init.kind === ts.SyntaxKind.FalseKeyword)
    return init.getText(src);
  if (
    ts.isArrayLiteralExpression(init) ||
    ts.isObjectLiteralExpression(init) ||
    ts.isAsExpression(init)
  ) {
    return truncate(clean(init.getText(src)), 90);
  }
  if (ts.isCallExpression(init)) return truncate(clean(init.expression.getText(src)) + '(…)', 60);
  if (ts.isNewExpression(init))
    return truncate('new ' + clean(init.expression.getText(src)) + '(…)', 60);
  return truncate(clean(init.getText(src)), 60);
}

/** Does this initializer look like a Zod schema? */
const isZod = (init, src) => Boolean(init) && /^z\./.test(clean(init.getText(src)));

function classify({ name, file, init, src, isServerAction }) {
  const tsx = file.endsWith('.tsx');
  const fnLike = init && (ts.isArrowFunction(init) || ts.isFunctionExpression(init));
  if (isZod(init, src)) return 'zod';
  if (isHook(name)) return 'hook';
  if (isServerAction) return 'action';
  if (tsx && isPascal(name)) return 'component';
  if (fnLike) return 'fn';
  if (isScreamingConst(name)) return 'const';
  return 'var';
}

function extractRoutes(node, src, file) {
  if (!ts.isCallExpression(node)) return;
  const callee = node.expression;
  if (!ts.isPropertyAccessExpression(callee)) return;
  const method = callee.name.getText(src).toLowerCase();
  if (!['get', 'post', 'put', 'patch', 'delete', 'use', 'all'].includes(method)) return;
  const obj = clean(callee.expression.getText(src));
  if (!/^(router|app)$/i.test(obj) && !/[Rr]outer$/.test(obj)) return;
  /** A handler reference, named rather than inlined — the whole point of the index. */
  const label = (a) => {
    if (ts.isIdentifier(a)) return a.text;
    if (ts.isCallExpression(a)) {
      // `authorize(PERMISSIONS.BRANCH_READ)` — the argument is the permission
      // gate, which is the single most useful fact about the route.
      const fn = truncate(clean(a.expression.getText(src)), 40);
      const arg = a.arguments[0] ? truncate(clean(a.arguments[0].getText(src)), 46) : '';
      return arg && !arg.includes('{') ? `${fn}(${arg})` : `${fn}(…)`;
    }
    if (ts.isPropertyAccessExpression(a)) return truncate(clean(a.getText(src)), 40);
    if (ts.isArrowFunction(a) || ts.isFunctionExpression(a)) return '<inline>';
    if (ts.isObjectLiteralExpression(a) || ts.isArrayLiteralExpression(a)) return '<literal>';
    return truncate(clean(a.getText(src)), 40);
  };

  // `app.use(middleware)` has no path argument. Only treat arg 0 as a path when
  // it actually is one, or the whole helmet/cors config lands in the table.
  const hasPath = ts.isStringLiteralLike(node.arguments[0]);
  const path = hasPath ? node.arguments[0].text : '*';
  const chain = node.arguments.slice(hasPath ? 1 : 0).map(label);
  routes.push({
    method: method.toUpperCase(),
    path,
    file,
    line: src.getLineAndCharacterOfPosition(node.getStart(src)).line + 1,
    chain,
  });
}

for (const file of files) {
  if (DECL_EXT.test(file)) continue;
  const text = readFileSync(join(ROOT, file), 'utf8');
  const src = ts.createSourceFile(
    file,
    text,
    ts.ScriptTarget.ESNext,
    true,
    file.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS
  );
  const moduleId = moduleIdOf(file);
  const isServerActionFile = /(^|\/)actions\.tsx?$/.test(file) && /^['"]use server['"]/m.test(text);

  let fileBanner = '';
  const lineOf = (node) => src.getLineAndCharacterOfPosition(node.getStart(src)).line + 1;

  // Test files are indexed for their shared helpers and fixtures, not for the
  // hundreds of throwaway locals inside each case.
  const isTest = /\.(test|spec)\.tsx?$/.test(file) || /\/tests?\//.test(file);
  const push = (row) => {
    if (isTest && !row.exported && row.kind !== 'fn') return;
    symbols.push({ module: moduleId, file, ...row });
  };

  for (const stmt of src.statements) {
    const { summary, banner } = docOf(stmt);
    if (banner && !fileBanner) fileBanner = banner;
    const exported = Boolean(ts.getCombinedModifierFlags(stmt) & ts.ModifierFlags.Export);

    if (ts.isFunctionDeclaration(stmt) && stmt.name) {
      const name = stmt.name.text;
      const kind = isHook(name)
        ? 'hook'
        : isServerActionFile && exported
          ? 'action'
          : file.endsWith('.tsx') && isPascal(name)
            ? 'component'
            : 'fn';
      push({
        name,
        kind,
        exported,
        line: lineOf(stmt),
        sig: sigOfFunctionLike(stmt, src),
        summary,
        async: Boolean(ts.getCombinedModifierFlags(stmt) & ts.ModifierFlags.Async),
      });
    } else if (ts.isVariableStatement(stmt)) {
      for (const d of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(d.name)) continue;
        const name = d.name.text;
        const init = d.initializer;
        const kind = classify({
          name,
          file,
          init,
          src,
          isServerAction: isServerActionFile && exported,
        });
        const sig =
          init && (ts.isArrowFunction(init) || ts.isFunctionExpression(init))
            ? sigOfFunctionLike(init, src)
            : d.type
              ? `: ${truncate(clean(d.type.getText(src)), 80)}`
              : constPreview(init, src);
        push({
          name,
          kind,
          exported,
          line: lineOf(d),
          sig,
          summary,
          async: Boolean(init?.modifiers?.some((m) => m.kind === ts.SyntaxKind.AsyncKeyword)),
        });
      }
    } else if (ts.isInterfaceDeclaration(stmt)) {
      const members = stmt.members.map((m) => clean(m.name?.getText(src) ?? '')).filter(Boolean);
      push({
        name: stmt.name.text,
        kind: 'interface',
        exported,
        line: lineOf(stmt),
        sig: truncate(`{ ${members.join(', ')} }`, 200),
        summary,
      });
    } else if (ts.isTypeAliasDeclaration(stmt)) {
      push({
        name: stmt.name.text,
        kind: 'type',
        exported,
        line: lineOf(stmt),
        sig: truncate(clean(stmt.type.getText(src)), 160),
        summary,
      });
    } else if (ts.isEnumDeclaration(stmt)) {
      push({
        name: stmt.name.text,
        kind: 'enum',
        exported,
        line: lineOf(stmt),
        sig: truncate(stmt.members.map((m) => clean(m.name.getText(src))).join(', '), 160),
        summary,
      });
    } else if (ts.isClassDeclaration(stmt) && stmt.name) {
      const members = stmt.members.map((m) => clean(m.name?.getText(src) ?? '')).filter(Boolean);
      push({
        name: stmt.name.text,
        kind: 'class',
        exported,
        line: lineOf(stmt),
        sig: truncate(`{ ${members.join(', ')} }`, 200),
        summary,
      });
    } else if (ts.isExportDeclaration(stmt) && stmt.moduleSpecifier) {
      const from = ts.isStringLiteralLike(stmt.moduleSpecifier) ? stmt.moduleSpecifier.text : '';
      if (!stmt.exportClause) barrels.push({ file, from, names: '*' });
      else if (ts.isNamedExports(stmt.exportClause)) {
        barrels.push({
          file,
          from,
          names: stmt.exportClause.elements.map((e) => e.name.text).join(', '),
        });
      }
    }
  }

  // Imports: which workspace packages this file depends on, and which contract
  // schemas it pulls in. Both feed the module and API docs.
  for (const stmt of src.statements) {
    if (!ts.isImportDeclaration(stmt) || !ts.isStringLiteralLike(stmt.moduleSpecifier)) continue;
    const from = stmt.moduleSpecifier.text;
    if (from.startsWith('@rcln/')) {
      if (!importGraph.has(file)) importGraph.set(file, new Set());
      importGraph.get(file).add(from);
    }
    if (from !== '@rcln/contracts') continue;
    const named = stmt.importClause?.namedBindings;
    if (!named || !ts.isNamedImports(named)) continue;
    if (!importedContracts.has(file)) importedContracts.set(file, new Set());
    for (const el of named.elements) importedContracts.get(file).add(el.name.text);
  }

  if (fileBanner) fileBanners.set(file, fileBanner);

  // Express route registrations, anywhere in the file.
  if (/routes?\.tsx?$/.test(file) || /\/routes\//.test(file) || /app\.ts$/.test(file)) {
    const visit = (n) => {
      extractRoutes(n, src, file);
      ts.forEachChild(n, visit);
    };
    ts.forEachChild(src, visit);
  }

  recordModule(moduleId, file, fileBanner);
}

// ---------------------------------------------------------------------------
// prisma schema
// ---------------------------------------------------------------------------

const PRISMA = 'packages/db/prisma/schema.prisma';
const prismaModels = [];
const prismaEnums = [];
if (existsSync(join(ROOT, PRISMA))) {
  const text = readFileSync(join(ROOT, PRISMA), 'utf8');
  const lines = text.split('\n');
  let current = null;
  lines.forEach((raw, i) => {
    const line = raw.trim();
    const model = line.match(/^model\s+(\w+)\s*\{/);
    const enm = line.match(/^enum\s+(\w+)\s*\{/);
    if (model) {
      current = { kind: 'model', name: model[1], line: i + 1, fields: [], attrs: [], mapped: '' };
      prismaModels.push(current);
      return;
    }
    if (enm) {
      current = { kind: 'enum', name: enm[1], line: i + 1, values: [] };
      prismaEnums.push(current);
      return;
    }
    if (!current) return;
    if (line === '}') {
      current = null;
      return;
    }
    if (!line || line.startsWith('//')) return;
    if (current.kind === 'enum') {
      current.values.push(line.split(/\s+/)[0]);
      return;
    }
    if (line.startsWith('@@')) {
      const map = line.match(/^@@map\("([^"]+)"\)/);
      if (map) current.mapped = map[1];
      else current.attrs.push(clean(line));
      return;
    }
    const f = line.match(/^(\w+)\s+([\w[\]?]+)/);
    if (f) {
      // A field whose type is another model is a relation, not a column. Keeping
      // the two apart is what makes the field list readable at a glance.
      const bare = f[2].replace(/[[\]?]/g, '');
      current.fields.push({ name: f[1], type: f[2], bare, raw: clean(line) });
    }
  });
}

/**
 * RLS coverage, so schema.md can flag a tenant table that has no policy.
 *
 * Most tables are not named in an `ALTER TABLE` statement at all — they are
 * elements of a PL/pgSQL array that a FOREACH loop then formats into one. So
 * this reads both: literal ALTERs, and the `<scope> text[] := ARRAY[...]`
 * declarations. The array's variable name doubles as the policy flavour
 * (org_scoped, branch_scoped, parent_scoped).
 *
 * This is a static read of the SQL, not proof the policy is live in Postgres.
 * `pnpm db:rls:check` is the authority; this only catches a table nobody wrote
 * a policy for.
 */
const RLS_SQL = 'packages/db/prisma/rls/enable-rls.sql';
const rlsTables = new Map(); // table -> scope label
if (existsSync(join(ROOT, RLS_SQL))) {
  const sql = readFileSync(join(ROOT, RLS_SQL), 'utf8');
  for (const m of sql.matchAll(/ALTER\s+TABLE\s+"?(\w+)"?\s+ENABLE\s+ROW\s+LEVEL\s+SECURITY/gi)) {
    rlsTables.set(m[1], 'explicit');
  }
  for (const m of sql.matchAll(/(\w+)\s+text\[\](\[\])?\s*:=\s*ARRAY\[([\s\S]*?)\n\s*\];/g)) {
    const [, varName, nested, body] = m;
    const scope = varName.replace(/_scoped$/, '');
    if (nested) {
      // text[][] rows are ARRAY['child', 'parent', 'fk'] — the child is table 0.
      for (const row of body.matchAll(/ARRAY\[\s*'([^']+)'/g)) rlsTables.set(row[1], scope);
    } else {
      for (const q of body.matchAll(/'([^']+)'/g)) rlsTables.set(q[1], scope);
    }
  }
}

/**
 * Tables consciously exempted from RLS, each with a written reason. check-rls.ts
 * owns this list; reading it here keeps schema.md from reporting a deliberate
 * exemption as a missing policy.
 */
const CHECK_RLS = 'packages/db/scripts/check-rls.ts';
const rlsExempt = new Map();
if (existsSync(join(ROOT, CHECK_RLS))) {
  const text = readFileSync(join(ROOT, CHECK_RLS), 'utf8');
  const block = text.match(/const EXEMPT: Record<string, string> = \{([\s\S]*?)\n\};/);
  if (block) {
    for (const m of block[1].matchAll(/^\s*(\w+):\s*(['"`])([\s\S]*?)\2,/gm)) {
      rlsExempt.set(m[1], truncate(clean(m[3]), 120));
    }
  }
}

// ---------------------------------------------------------------------------
// render
// ---------------------------------------------------------------------------

const STAMP = '<!-- generated by .kb/generate.mjs — do not edit by hand -->';
const out = new Map();

// ---- symbols.tsv : the primary grep target -------------------------------
{
  const rows = [...symbols].sort(
    (a, b) => a.name.localeCompare(b.name) || a.file.localeCompare(b.file)
  );
  const body = rows
    .map((s) =>
      [
        s.name,
        s.kind + (s.async ? '/async' : ''),
        s.exported ? 'export' : 'local',
        `${s.file}:${s.line}`,
        s.module,
        clean(s.sig),
        truncate(clean(s.summary), 120),
      ].join('\t')
    )
    .join('\n');
  out.set(
    'symbols.tsv',
    `# generated by .kb/generate.mjs — do not edit by hand\n` +
      `# name\tkind\tvisibility\tlocation\tmodule\tsignature\tsummary\n` +
      `${body}\n`
  );
}

// ---- INDEX.md : module routing table -------------------------------------
{
  const modules = [...moduleMeta.keys()].sort();
  const lines = [
    '# .kb index',
    '',
    STAMP,
    '',
    `${symbols.length} symbols · ${files.length} files · ${modules.length} modules · ${routes.length} route registrations`,
    '',
    'Grep `symbols.tsv` first. Open a module file only when you need signatures or neighbours.',
    '',
    '| module | kb file | exported symbols |',
    '| --- | --- | --- |',
  ];
  for (const m of modules) {
    const exported = symbols.filter((s) => s.module === m && s.exported).map((s) => s.name);
    lines.push(
      `| \`${m}\` | [${kbFileNameOf(m)}](Symbols/${kbFileNameOf(m)}) | ${exported.length ? exported.map((n) => `\`${n}\``).join(' ') : '—'} |`
    );
  }
  // Barrel files are the public surface of each workspace package — what you
  // may import from `@rcln/db` without reaching past the entry point.
  const packageBarrels = barrels.filter((b) => /\/index\.tsx?$/.test(b.file));
  if (packageBarrels.length) {
    lines.push(
      '',
      '## Package entry points',
      '',
      '| barrel | re-exports | from |',
      '| --- | --- | --- |'
    );
    for (const b of packageBarrels.sort((a, x) => a.file.localeCompare(x.file))) {
      lines.push(
        `| \`${b.file}\` | ${
          b.names === '*'
            ? 'everything'
            : b.names
                .split(', ')
                .map((n) => `\`${n}\``)
                .join(' ')
        } | \`${b.from}\` |`
      );
    }
  }
  lines.push(
    '',
    '## Other generated files',
    '',
    '- [APIs/\\_index.md](APIs/_index.md) — HTTP surface and middleware chains',
    '- [Database/\\_index.md](Database/_index.md) — Prisma models, fields, RLS coverage',
    '- [09_Roles_and_Permissions.md](09_Roles_and_Permissions.md) — role × permission matrix',
    '- [symbols.tsv](symbols.tsv) — flat symbol index',
    ''
  );
  out.set('INDEX.md', lines.join('\n'));
}

// ---- modules/*.md ---------------------------------------------------------
const KIND_ORDER = [
  'component',
  'hook',
  'action',
  'fn',
  'class',
  'zod',
  'const',
  'var',
  'interface',
  'type',
  'enum',
];
for (const [moduleId, meta] of moduleMeta) {
  const mine = symbols.filter((s) => s.module === moduleId);
  const lines = [`# \`${moduleId}\``, '', STAMP, ''];
  if (meta.banner) lines.push(`> ${truncate(firstSentence(meta.banner), 400)}`, '');
  lines.push(
    `Files: ${[...meta.files]
      .sort()
      .map((f) => `\`${f}\``)
      .join(' · ')}`,
    ''
  );

  const byKind = new Map();
  for (const s of mine) {
    if (!byKind.has(s.kind)) byKind.set(s.kind, []);
    byKind.get(s.kind).push(s);
  }
  const kinds = [...byKind.keys()].sort((a, b) => {
    const ia = KIND_ORDER.indexOf(a),
      ib = KIND_ORDER.indexOf(b);
    return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
  });
  for (const kind of kinds) {
    lines.push(`## ${kind}`, '', '| name | signature | at | notes |', '| --- | --- | --- | --- |');
    for (const s of byKind.get(kind).sort((a, b) => a.name.localeCompare(b.name))) {
      const name = s.exported ? `\`${s.name}\`` : `\`${s.name}\` <sub>local</sub>`;
      const sig = s.sig ? `\`${clean(s.sig).replace(/\|/g, '\\|')}\`` : '';
      lines.push(
        `| ${name} | ${sig} | \`${s.file}:${s.line}\` | ${truncate(clean(s.summary), 160).replace(/\|/g, '\\|')} |`
      );
    }
    lines.push('');
  }

  const notePath = join(KB, 'notes', kbFileNameOf(moduleId));
  if (existsSync(notePath))
    lines.push(
      `## Notes`,
      '',
      `See [notes/${kbFileNameOf(moduleId)}](../notes/${kbFileNameOf(moduleId)}).`,
      ''
    );

  out.set(`Symbols/${kbFileNameOf(moduleId)}`, lines.join('\n'));
}

// ---- APIs/ : one file per route group, plus an index ----------------------
{
  /** `apps/api/src/routes/v1/branches.routes.ts` -> `branches`. */
  const groupOf = (file) => {
    const base = file
      .split('/')
      .pop()
      .replace(/\.tsx?$/, '');
    return base.replace(/\.routes$/, '');
  };

  const byGroup = new Map();
  for (const r of routes) {
    const g = groupOf(r.file);
    if (!byGroup.has(g)) byGroup.set(g, []);
    byGroup.get(g).push(r);
  }

  // Mount prefixes: a `use` row whose handler is a router identifier tells us
  // where that group hangs off the tree. Without this every path reads as if it
  // were rooted, and `/login` is not an endpoint anyone can call.
  const mounts = routes
    .filter((r) => r.method === 'USE' && r.path !== '*' && r.chain.length === 1)
    .map((r) => ({ prefix: r.path, target: r.chain[0], file: r.file }));

  const index = [
    '# HTTP surface',
    '',
    STAMP,
    '',
    `${routes.filter((r) => r.method !== 'USE').length} endpoints across ${byGroup.size} route files.`,
    'Paths are as registered — prepend the mount prefixes below for the callable URL.',
    '',
    '## Mount points',
    '',
    '| prefix | mounts | declared in |',
    '| --- | --- | --- |',
  ];
  for (const m of mounts) index.push(`| \`${m.prefix}\` | \`${m.target}\` | \`${m.file}\` |`);

  index.push('', '## Route groups', '', '| group | endpoints | file |', '| --- | --- | --- |');
  for (const g of [...byGroup.keys()].sort()) {
    const rs = byGroup.get(g);
    const endpoints = rs.filter((r) => r.method !== 'USE').length;
    index.push(`| [${g}](${g}.md) | ${endpoints} | \`${rs[0].file}\` |`);
  }

  index.push(
    '',
    '## Every route, flat',
    '',
    '| method | path | middleware → handler | at |',
    '| --- | --- | --- | --- |'
  );
  for (const r of [...routes].sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line)) {
    index.push(
      `| ${r.method} | \`${r.path}\` | ${r.chain.map((c) => `\`${c}\``).join(' → ') || '—'} | \`${r.file}:${r.line}\` |`
    );
  }
  index.push('');
  out.set('APIs/_index.md', index.join('\n'));

  for (const [g, rs] of byGroup) {
    const file = rs[0].file;
    const meta = moduleMeta.get(moduleIdOf(file));
    const lines = [`# API — \`${g}\``, '', STAMP, '', `Source: \`${file}\``, ''];

    // The route file's own banner comment is usually the best available
    // statement of what this group is for.
    const banner = fileBanners.get(file);
    if (banner) lines.push(`> ${truncate(banner, 700)}`, '');

    lines.push('| method | path | middleware → handler | at |', '| --- | --- | --- | --- |');
    for (const r of rs.sort((a, b) => a.line - b.line)) {
      lines.push(
        `| ${r.method} | \`${r.path}\` | ${r.chain.map((c) => `\`${c}\``).join(' → ') || '—'} | \`${r.file}:${r.line}\` |`
      );
    }

    // Zod contracts referenced by this file are the request/response schemas.
    const localSchemas = symbols.filter((s) => s.file === file && s.kind === 'zod');
    if (localSchemas.length) {
      lines.push('', '## Schemas declared here', '', '| name | at |', '| --- | --- |');
      for (const s of localSchemas.sort((a, b) => a.line - b.line)) {
        lines.push(`| \`${s.name}\` | \`${s.file}:${s.line}\` |`);
      }
    }

    const contracts = importedContracts.get(file);
    if (contracts?.size) {
      lines.push(
        '',
        '## Contracts imported from `@rcln/contracts`',
        '',
        [...contracts]
          .sort()
          .map((c) => `\`${c}\``)
          .join(' · '),
        ''
      );
    }

    if (meta) {
      lines.push(
        '',
        `Symbols in this module: [${kbFileNameOf(meta ? moduleIdOf(file) : '')}](../Symbols/${kbFileNameOf(moduleIdOf(file))})`,
        ''
      );
    }
    out.set(`APIs/${g}.md`, lines.join('\n'));
  }
}

// ---- Database/ : index + one file per model -------------------------------
const modelNames = new Set(prismaModels.map((m) => m.name));
{
  const lines = [
    '# Database schema',
    '',
    STAMP,
    '',
    `Source: \`${PRISMA}\` · RLS policies: \`${RLS_SQL}\``,
    '',
    `${prismaModels.length} models · ${prismaEnums.length} enums · ${[...prismaModels].filter((m) => m.fields.some((f) => f.name === 'organizationId')).length} tenant-scoped.`,
    'One file per model in this directory; the tables below are the overview.',
    '',
  ];
  lines.push('| model | table | org col | RLS | columns |', '| --- | --- | --- | --- | --- |');
  for (const m of prismaModels) {
    const table = m.mapped || m.name;
    const tenant = m.fields.some((f) => f.name === 'organizationId');
    const rls = rlsTables.get(table);
    const rlsCell = rls ? rls : rlsExempt.has(table) ? 'exempt' : tenant ? '**MISSING**' : '—';
    const cols = m.fields.filter((f) => !modelNames.has(f.bare));
    lines.push(
      `| [\`${m.name}\`](${m.name}.md) | \`${table}\` | ${tenant ? 'yes' : '—'} | ${rlsCell} | ${cols.map((f) => `\`${f.name}\``).join(' ')} |`
    );
  }
  if (rlsExempt.size) {
    lines.push(
      '',
      '## RLS exemptions',
      '',
      `Source: \`${CHECK_RLS}\` — a table here is gated in the application layer instead.`,
      '',
      '| table | reason |',
      '| --- | --- |'
    );
    for (const [t, why] of [...rlsExempt].sort())
      lines.push(`| \`${t}\` | ${why.replace(/\|/g, '\\|')} |`);
  }
  lines.push('', '## relations', '', '| model | relation fields |', '| --- | --- |');
  for (const m of prismaModels) {
    const rels = m.fields.filter((f) => modelNames.has(f.bare));
    if (rels.length)
      lines.push(`| \`${m.name}\` | ${rels.map((f) => `\`${f.name}: ${f.type}\``).join(' ')} |`);
  }
  if (prismaEnums.length) {
    lines.push('', '## enums', '', '| enum | values |', '| --- | --- |');
    for (const e of prismaEnums)
      lines.push(`| \`${e.name}\` | ${e.values.map((v) => `\`${v}\``).join(' ')} |`);
  }
  lines.push('');
  out.set('Database/_index.md', lines.join('\n'));
}

// One file per model. An ERD per table rather than one 26-model diagram nobody
// can read: only this model and its immediate neighbours.
for (const m of prismaModels) {
  const table = m.mapped || m.name;
  const tenant = m.fields.some((f) => f.name === 'organizationId');
  const rls = rlsTables.get(table);
  const cols = m.fields.filter((f) => !modelNames.has(f.bare));
  const rels = m.fields.filter((f) => modelNames.has(f.bare));

  const lines = [
    `# \`${m.name}\` → \`${table}\``,
    '',
    STAMP,
    '',
    `Declared at \`${PRISMA}:${m.line}\`.`,
    '',
    '| property | value |',
    '| --- | --- |',
    `| table | \`${table}\` |`,
    `| tenant-scoped | ${tenant ? 'yes — has `organizationId`' : 'no'} |`,
    `| RLS | ${rls ? `\`${rls}\` policy` : rlsExempt.has(table) ? `exempt — ${rlsExempt.get(table)}` : tenant ? '**MISSING — this is a tenant-isolation defect**' : 'not applicable'} |`,
    `| columns | ${cols.length} |`,
    `| relations | ${rels.length} |`,
    '',
    '## Columns',
    '',
    '| column | type | definition |',
    '| --- | --- | --- |',
  ];
  for (const f of cols) {
    lines.push(`| \`${f.name}\` | \`${f.type}\` | \`${f.raw.replace(/\|/g, '\\|')}\` |`);
  }

  if (rels.length) {
    lines.push('', '## Relations', '', '| field | target | definition |', '| --- | --- | --- |');
    for (const f of rels) {
      lines.push(
        `| \`${f.name}\` | [\`${f.bare}\`](${f.bare}.md) | \`${f.raw.replace(/\|/g, '\\|')}\` |`
      );
    }
  }

  if (m.attrs.length) {
    lines.push('', '## Indexes and constraints', '');
    for (const a of m.attrs) lines.push(`- \`${a}\``);
  }

  const neighbours = [...new Set(rels.map((f) => f.bare))];
  if (neighbours.length) {
    lines.push('', '## Neighbourhood', '', '```mermaid', 'erDiagram');
    for (const n of neighbours) lines.push(`    ${m.name} }o--o{ ${n} : relates`);
    lines.push('```');
  }
  lines.push('');
  out.set(`Database/${m.name}.md`, lines.join('\n'));
}

// ---- 09_Roles_and_Permissions.md ------------------------------------------
/**
 * The role definitions are computed, not literal — ORG_ADMIN is
 * `ALL_PERMISSIONS.filter(...)`, which no static parse can resolve. So this
 * imports the built package and asks it. That makes the matrix exact, at the
 * cost of depending on `packages/permissions/dist`: if the build is missing the
 * section degrades to a note rather than guessing.
 */
{
  const DIST = join(ROOT, 'packages/permissions/dist/index.js');
  const lines = ['# Roles and permissions', '', STAMP, ''];
  let perms = null;
  if (existsSync(DIST)) {
    try {
      perms = await import(pathToFileURL(DIST).href);
    } catch (err) {
      lines.push(`> Could not load \`packages/permissions/dist\`: ${clean(err.message)}`, '');
    }
  } else {
    lines.push(
      '> `packages/permissions/dist` is not built, so the matrix below is omitted.',
      '> Run `pnpm build` (or `pnpm --filter @rcln/permissions build`) and `pnpm kb`.',
      ''
    );
  }

  if (perms?.SYSTEM_ROLE_DEFINITIONS) {
    const defs = perms.SYSTEM_ROLE_DEFINITIONS;
    const all = perms.ALL_PERMISSIONS ?? [];
    lines.push(
      `${defs.length} system roles · ${all.length} permissions.`,
      '',
      'Source of truth: `packages/permissions/src/roles.ts` and `packages/permissions/src/codes.ts`,',
      'seeded into `roles` / `permissions` / `role_permissions` by `packages/db/prisma/seed.ts`.',
      'System roles have `organizationId = null` and are never mutated by a tenant —',
      'a tenant clones one into an org-scoped role instead.',
      '',
      '## Roles',
      '',
      '| code | name | scope | permissions | description |',
      '| --- | --- | --- | --- | --- |'
    );
    for (const d of defs) {
      lines.push(
        `| \`${d.code}\` | ${d.name} | ${d.scopeLevel} | ${d.permissions.length} / ${all.length} | ${clean(d.description).replace(/\|/g, '\\|')} |`
      );
    }

    // Matrix, one section per module, or a single 83-row table nobody reads.
    const moduleOf = perms.moduleOf ?? ((p) => String(p).split('.')[0]);
    const byModule = new Map();
    for (const p of all) {
      const mod = moduleOf(p);
      if (!byModule.has(mod)) byModule.set(mod, []);
      byModule.get(mod).push(p);
    }
    const held = new Map(defs.map((d) => [d.code, new Set(d.permissions)]));
    const header = `| permission | ${defs.map((d) => d.code.replace(/_/g, ' ')).join(' | ')} |`;
    const divider = `| --- | ${defs.map(() => '---').join(' | ')} |`;

    lines.push(
      '',
      '## Access matrix',
      '',
      '`Y` = granted by the system role definition. Blank = not granted.',
      ''
    );
    for (const mod of [...byModule.keys()].sort()) {
      lines.push(`### ${mod}`, '', header, divider);
      for (const p of byModule.get(mod).sort()) {
        lines.push(
          `| \`${p}\` | ${defs.map((d) => (held.get(d.code).has(p) ? 'Y' : '')).join(' | ')} |`
        );
      }
      lines.push('');
    }

    lines.push(
      '## Privilege hierarchy',
      '',
      '```mermaid',
      'flowchart TD',
      ...defs
        .filter((d) => d.scopeLevel === 'PLATFORM')
        .map((d) => `    ${d.code}["${d.name} · platform"]`),
      ...defs
        .filter((d) => d.scopeLevel === 'ORGANIZATION')
        .map((d) => `    ${d.code}["${d.name} · org"]`),
      ...defs
        .filter((d) => d.scopeLevel === 'BRANCH')
        .map((d) => `    ${d.code}["${d.name} · branch"]`),
      ...defs
        .filter((d) => d.scopeLevel === 'PLATFORM')
        .flatMap((p) =>
          defs
            .filter((d) => d.scopeLevel === 'ORGANIZATION')
            .map((o) => `    ${p.code} --> ${o.code}`)
        ),
      ...defs
        .filter((d) => d.code === 'ORG_OWNER')
        .flatMap(() =>
          defs.filter((d) => d.scopeLevel === 'BRANCH').map((b) => `    ORG_OWNER --> ${b.code}`)
        ),
      '```',
      '',
      'Scope is not inheritance. A `BRANCH` role grants its permissions only inside the',
      'branches named on that `membership_roles` row; a NULL `branch_id` means every branch',
      'in the organization. The arrows above show privilege breadth, not a delegation chain.',
      ''
    );
  }
  out.set('09_Roles_and_Permissions.md', lines.join('\n'));
}

// ---- Modules/ : narrative from modules.json, facts from source ------------
/**
 * The one hybrid file set. Purpose, features and limitations cannot be parsed
 * out of code, so they live in the hand-edited `.kb/modules.json`; everything
 * else — symbols, routes, tables, permissions — is resolved here so it cannot
 * drift. Add a module by adding an entry to that file.
 */
{
  const MANIFEST = join(KB, 'modules.json');
  if (existsSync(MANIFEST)) {
    const manifestModules = JSON.parse(readFileSync(MANIFEST, 'utf8'));
    const catalog = [
      '# Module catalog',
      '',
      STAMP,
      '',
      'Narrative from `.kb/modules.json`; symbol, route and table counts resolved from source.',
      '',
      '| module | layer | purpose | endpoints | tables |',
      '| --- | --- | --- | --- | --- |',
    ];

    for (const mod of manifestModules) {
      const globs = mod.paths ?? [];
      const matches = (f) => globs.some((g) => f.startsWith(g));
      const mine = symbols.filter((s) => matches(s.file));
      const myRoutes = routes.filter((r) => matches(r.file) && r.method !== 'USE');
      const myFiles = [...new Set(mine.map((s) => s.file))].sort();

      catalog.push(
        `| [${mod.name}](Modules/${mod.name}.md) | ${mod.layer ?? '—'} | ${clean(mod.purpose ?? '').replace(/\|/g, '\\|')} | ${myRoutes.length} | ${(mod.tables ?? []).length} |`
      );

      const lines = [
        `# ${mod.name}`,
        '',
        STAMP,
        '',
        `**Layer:** ${mod.layer ?? '—'}  `,
        `**Status:** ${mod.status ?? 'unknown'}`,
        '',
        '## Purpose',
        '',
        mod.purpose ?? '_Not documented in `.kb/modules.json`._',
        '',
      ];

      if (mod.features?.length) {
        lines.push('## Features', '', ...mod.features.map((f) => `- ${f}`), '');
      }
      if (mod.userActions?.length) {
        lines.push('## User actions', '', ...mod.userActions.map((f) => `- ${f}`), '');
      }
      if (mod.businessRules?.length) {
        lines.push(
          '## Business rules',
          '',
          ...mod.businessRules.map(
            (r) => `- [${r}](../BusinessRules/${mod.name}.md#${String(r).toLowerCase()})`
          ),
          ''
        );
      }

      if (myRoutes.length) {
        lines.push('## API surface', '', '| method | path | at |', '| --- | --- | --- |');
        for (const r of myRoutes.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line)) {
          lines.push(`| ${r.method} | \`${r.path}\` | \`${r.file}:${r.line}\` |`);
        }
        lines.push('');
      }

      if (mod.tables?.length) {
        lines.push('## Database impact', '', '| model | RLS |', '| --- | --- |');
        for (const t of mod.tables) {
          const model = prismaModels.find((p) => p.name === t);
          const tbl = model ? model.mapped || model.name : t;
          const r = rlsTables.get(tbl);
          lines.push(
            `| [\`${t}\`](../Database/${t}.md) | ${r ?? (rlsExempt.has(tbl) ? 'exempt' : '—')} |`
          );
        }
        lines.push('');
      }

      if (mod.permissions?.length) {
        lines.push('## Permissions', '', mod.permissions.map((p) => `\`${p}\``).join(' · '), '');
      }

      if (myFiles.length) {
        lines.push('## Source files', '', ...myFiles.map((f) => `- \`${f}\``), '');
      }

      const deps = [...new Set(myFiles.flatMap((f) => [...(importGraph.get(f) ?? [])]))].sort();
      if (deps.length) {
        lines.push('## Workspace dependencies', '', deps.map((d) => `\`${d}\``).join(' · '), '');
      }

      if (mod.limitations?.length) {
        lines.push('## Known limitations', '', ...mod.limitations.map((f) => `- ${f}`), '');
      }

      lines.push(
        '## Exported symbols',
        '',
        '| name | kind | at |',
        '| --- | --- | --- |',
        ...mine
          .filter((s) => s.exported)
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((s) => `| \`${s.name}\` | ${s.kind} | \`${s.file}:${s.line}\` |`),
        ''
      );

      out.set(`Modules/${mod.name}.md`, lines.join('\n'));
    }
    catalog.push('');
    out.set('06_Module_Catalog.md', catalog.join('\n'));
  }
}

// ---------------------------------------------------------------------------
// write / check
// ---------------------------------------------------------------------------

const hash = (s) => createHash('sha1').update(s).digest('hex').slice(0, 12);

/**
 * The previous manifest is the record of what this script owns. Sweeping by
 * "everything in the directory that I did not just write" would delete the
 * hand-written pages that live alongside the generated ones — the absorbed
 * `Database/schema-design.md`, for one. Only a file that was generated last
 * time and is not generated this time is stale.
 */
const MANIFEST_PATH = join(KB, 'manifest.json');
let previous = {};
if (existsSync(MANIFEST_PATH)) {
  try {
    previous = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  } catch {
    previous = {}; // corrupt manifest just means no sweep this run
  }
}

const manifest = Object.fromEntries([...out].map(([k, v]) => [k, hash(v)]).sort());
out.set('manifest.json', `${JSON.stringify(manifest, null, 2)}\n`);

const changed = [];
for (const [rel, content] of out) {
  const abs = join(KB, rel);
  const existing = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (existing === content) continue;
  changed.push(rel);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
}

for (const rel of Object.keys(previous)) {
  if (out.has(rel)) continue;
  const abs = join(KB, rel);
  if (!existsSync(abs)) continue;
  changed.push(`${rel} (removed)`);
  if (!CHECK) rmSync(abs);
}

if (CHECK) {
  if (changed.length) {
    console.error(`.kb is stale (${changed.length} file(s)). Run: pnpm kb`);
    for (const c of changed.slice(0, 20)) console.error(`  ${c}`);
    process.exit(1);
  }
  if (!QUIET) console.log('.kb is up to date.');
  process.exit(0);
}

if (changed.length || !QUIET) {
  console.log(
    `.kb: ${symbols.length} symbols, ${moduleMeta.size} modules, ${routes.length} routes · ${changed.length} file(s) written`
  );
}
