-- ===========================================================================
-- CE-3 · 2 of 2 — the encounter and its sections.
--
--   encounters          org + branch scoped, PHI in every text column
--   encounter_sections  org + branch scoped, PHI — the descriptor answers
--
-- ⚠️ FOUR BRAND-NEW ENUM TYPES, SO THE CHECK CONSTRAINTS BELOW MAY NAME THEIR
--   MEMBERS IN THIS SAME TRANSACTION (CD-9). The one `ALTER TYPE … ADD VALUE`
--   this phase needs — `NumberSequenceType.ENCOUNTER` — is migration 1 and is
--   deliberately not here.
--
-- ⚠️ `encounter_follow_up_recommendations.encounter_id` BECOMES NOT NULL HERE.
--   The column has been nullable since CE-1 with no writer at all: CE-4 is what
--   fills the table, so it is empty on every deployment and the tightening
--   needs no backfill. This is the last migration in which that is true.
--
-- Generated by `prisma migrate diff`, then extended by hand. The hand-written
-- half starts where it says so.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "ClinicalDurationUnit" AS ENUM ('HOURS', 'DAYS', 'WEEKS', 'MONTHS', 'YEARS');

-- CreateEnum
CREATE TYPE "ClinicalOnset" AS ENUM ('SUDDEN', 'GRADUAL', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "ConsultationSectionType" AS ENUM ('CHIEF_COMPLAINT', 'SYMPTOMS', 'HISTORY', 'EXAMINATION', 'VISUAL_MAPPING', 'DIAGNOSIS', 'PROCEDURE', 'PRESCRIPTION', 'INVESTIGATION', 'ADVICE', 'REFERRAL', 'CLINICAL_NOTES', 'ATTACHMENTS', 'FOLLOW_UP');

-- CreateEnum
CREATE TYPE "EncounterStatus" AS ENUM ('DRAFT', 'FINALIZED', 'AMENDED', 'CANCELLED');

-- AlterTable
ALTER TABLE "encounter_follow_up_recommendations" ALTER COLUMN "encounter_id" SET NOT NULL;

-- CreateTable
CREATE TABLE "encounters" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "patient_id" UUID NOT NULL,
    "appointment_id" UUID,
    "clinical_episode_id" UUID NOT NULL,
    "doctor_profile_id" UUID NOT NULL,
    "encounter_number" VARCHAR(32),
    "template_id" UUID NOT NULL,
    "template_version_id" UUID NOT NULL,
    "template_snapshot" JSONB NOT NULL,
    "status" "EncounterStatus" NOT NULL DEFAULT 'DRAFT',
    "chief_complaint" TEXT,
    "chief_complaint_duration_value" SMALLINT,
    "chief_complaint_duration_unit" "ClinicalDurationUnit",
    "onset" "ClinicalOnset",
    "clinical_notes" TEXT,
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finalized_at" TIMESTAMPTZ(6),
    "finalized_by" UUID,
    "amends_encounter_id" UUID,
    "amended_at" TIMESTAMPTZ(6),
    "amendment_reason" TEXT,
    "cancelled_at" TIMESTAMPTZ(6),
    "cancelled_by" UUID,
    "cancelled_reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "encounters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_sections" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "section_type" "ConsultationSectionType" NOT NULL,
    "section_key" VARCHAR(64) NOT NULL,
    "data" JSONB NOT NULL DEFAULT '{}',
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_sections_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "encounters_organization_id_patient_id_started_at_idx" ON "encounters"("organization_id", "patient_id", "started_at");

-- CreateIndex
CREATE INDEX "encounters_organization_id_clinical_episode_id_started_at_idx" ON "encounters"("organization_id", "clinical_episode_id", "started_at");

-- CreateIndex
CREATE INDEX "encounters_organization_id_doctor_profile_id_status_idx" ON "encounters"("organization_id", "doctor_profile_id", "status");

-- CreateIndex
CREATE INDEX "encounters_organization_id_template_version_id_idx" ON "encounters"("organization_id", "template_version_id");

-- CreateIndex
CREATE UNIQUE INDEX "encounters_organization_id_branch_id_encounter_number_key" ON "encounters"("organization_id", "branch_id", "encounter_number");

-- CreateIndex
CREATE UNIQUE INDEX "encounters_organization_id_id_key" ON "encounters"("organization_id", "id");

-- CreateIndex
CREATE INDEX "encounter_sections_organization_id_encounter_id_display_ord_idx" ON "encounter_sections"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE UNIQUE INDEX "encounter_sections_organization_id_encounter_id_section_key_key" ON "encounter_sections"("organization_id", "encounter_id", "section_key");

-- CreateIndex
CREATE INDEX "encounter_follow_up_recommendations_organization_id_encount_idx" ON "encounter_follow_up_recommendations"("organization_id", "encounter_id");

-- AddForeignKey
ALTER TABLE "encounter_follow_up_recommendations" ADD CONSTRAINT "encounter_follow_up_recommendations_organization_id_encoun_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_patient_id_fkey" FOREIGN KEY ("organization_id", "patient_id") REFERENCES "patients"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_appointment_id_fkey" FOREIGN KEY ("organization_id", "appointment_id") REFERENCES "appointments"("organization_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_clinical_episode_id_fkey" FOREIGN KEY ("organization_id", "clinical_episode_id") REFERENCES "clinical_episodes"("organization_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_doctor_profile_id_fkey" FOREIGN KEY ("organization_id", "doctor_profile_id") REFERENCES "doctor_profiles"("organization_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "consultation_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_template_version_id_fkey" FOREIGN KEY ("template_version_id") REFERENCES "consultation_template_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_finalized_by_fkey" FOREIGN KEY ("finalized_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_cancelled_by_fkey" FOREIGN KEY ("cancelled_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounters" ADD CONSTRAINT "encounters_organization_id_amends_encounter_id_fkey" FOREIGN KEY ("organization_id", "amends_encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "encounter_sections" ADD CONSTRAINT "encounter_sections_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_sections" ADD CONSTRAINT "encounter_sections_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_sections" ADD CONSTRAINT "encounter_sections_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- THE HAND-WRITTEN HALF
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- AT MOST ONE LIVE ENCOUNTER PER APPOINTMENT.
--
-- ⚠️ THE SECOND "START CONSULTATION" CLICK IS WHAT THIS REFUSES. Without it a
--   double submit — or two tabs, or a doctor and a resident on the same visit —
--   opens two records of one visit, and which one the prescription, the
--   invoice and the follow-up hang off is a race nobody can see afterwards.
--
-- AMENDED and CANCELLED rows are excluded because neither is live: an amendment
-- supersedes its original (CD-2), so the original and its correction cite the
-- same appointment on purpose, and exactly one of them is current.
--
-- Prisma cannot express a partial index, which is why this is here and not in
-- the model.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "encounters_one_live_per_appointment"
  ON "encounters" ("organization_id", "appointment_id")
  WHERE "appointment_id" IS NOT NULL
    AND "deleted_at" IS NULL
    AND "status" IN ('DRAFT', 'FINALIZED');

-- ---------------------------------------------------------------------------
-- AT MOST ONE LIVE AMENDMENT PER AMENDED ENCOUNTER.
--
-- Two live corrections of one record is two versions of the truth with nothing
-- to choose between them. A CANCELLED amendment is excluded so that an
-- abandoned correction does not block a real one.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "encounters_one_live_amendment"
  ON "encounters" ("organization_id", "amends_encounter_id")
  WHERE "amends_encounter_id" IS NOT NULL
    AND "deleted_at" IS NULL
    AND "status" <> 'CANCELLED';

-- ---------------------------------------------------------------------------
-- THE LIFECYCLE, AS THE DATABASE SEES IT.
--
-- ⚠️ A FINALIZED ROW WITH NO `finalized_at` IS THE BUG THIS REFUSES, and it is
--   what a half-written transaction leaves behind. The record would read as
--   signed in every screen and sort to the bottom of every date-ordered list.
--
-- DRAFT carries none of the finalization facts. FINALIZED and AMENDED carry all
-- of them — an AMENDED row was necessarily finalized first, because nothing
-- amends a draft; a draft is edited. CANCELLED carries a cancellation instead.
-- ---------------------------------------------------------------------------
ALTER TABLE "encounters"
  ADD CONSTRAINT "encounters_lifecycle_facts"
  CHECK (
    ("status" = 'DRAFT'
       AND "finalized_at" IS NULL AND "finalized_by" IS NULL
       AND "encounter_number" IS NULL
       AND "amended_at" IS NULL AND "cancelled_at" IS NULL)
    OR ("status" = 'FINALIZED'
       AND "finalized_at" IS NOT NULL AND "finalized_by" IS NOT NULL
       AND "encounter_number" IS NOT NULL
       AND "amended_at" IS NULL AND "cancelled_at" IS NULL)
    OR ("status" = 'AMENDED'
       AND "finalized_at" IS NOT NULL AND "finalized_by" IS NOT NULL
       AND "encounter_number" IS NOT NULL
       AND "amended_at" IS NOT NULL AND "cancelled_at" IS NULL)
    -- A consultation is cancelled from DRAFT and never from FINALIZED: a
    -- finalized record is corrected by an amendment, never withdrawn. So a
    -- CANCELLED row carries no finalization facts and burnt no number.
    OR ("status" = 'CANCELLED'
       AND "finalized_at" IS NULL AND "finalized_by" IS NULL
       AND "encounter_number" IS NULL
       AND "amended_at" IS NULL AND "cancelled_at" IS NOT NULL)
  );

-- An amendment says why. "The record changed and nobody said why" is the
-- failure an amendment trail exists to prevent.
ALTER TABLE "encounters"
  ADD CONSTRAINT "encounters_amendment_reason_present"
  CHECK (
    ("amends_encounter_id" IS NULL AND "amendment_reason" IS NULL)
    OR ("amends_encounter_id" IS NOT NULL AND "amendment_reason" IS NOT NULL)
  );

-- ⚠️ A DURATION OF "3" OF NOTHING IS NOT A DURATION. Value and unit travel
--   together or not at all; storing one without the other renders as a number
--   with no meaning on a clinical record.
ALTER TABLE "encounters"
  ADD CONSTRAINT "encounters_chief_complaint_duration_pair"
  CHECK (
    ("chief_complaint_duration_value" IS NULL AND "chief_complaint_duration_unit" IS NULL)
    OR ("chief_complaint_duration_value" IS NOT NULL AND "chief_complaint_duration_unit" IS NOT NULL)
  );

ALTER TABLE "encounters"
  ADD CONSTRAINT "encounters_chief_complaint_duration_positive"
  CHECK ("chief_complaint_duration_value" IS NULL OR "chief_complaint_duration_value" > 0);

-- An encounter never amends itself. Cheap to state, and the shape a
-- copy-and-edit bug produces.
ALTER TABLE "encounters"
  ADD CONSTRAINT "encounters_amends_is_not_self"
  CHECK ("amends_encounter_id" IS NULL OR "amends_encounter_id" <> "id");

-- ---------------------------------------------------------------------------
-- RLS — org + branch scoped, both loops, both tables.
--
-- ⚠️ `branch_id` IS NOT NULL ON BOTH, SO THE BRANCH POLICY IS ABSOLUTE — the
--   `branch_id IS NULL OR` half is dead code here, as it is for the invoice and
--   inventory tables. A doctor scoped to one site cannot read what another site
--   wrote about a patient, even by guessing a primary key.
--
--   That is the opposite call from `clinical_episodes`, and deliberately: the
--   JOURNEY follows the person across a hospital group (ADR-0016), the VISIT
--   belongs to the place it happened at.
--
-- The canonical copy of these policies is `prisma/rls/enable-rls.sql`; this is
-- the stanza for the two new tables, as the convention requires.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  org_branch_scoped text[] := ARRAY[
    'encounters',
    'encounter_sections'
  ];
BEGIN
  FOREACH t IN ARRAY org_branch_scoped LOOP
    EXECUTE format('ALTER TABLE %I ENABLE   ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', t);

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING      (organization_id = app_current_org())
        WITH CHECK (organization_id = app_current_org())
    $f$, t);

    EXECUTE format('DROP POLICY IF EXISTS branch_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY branch_isolation ON %I AS RESTRICTIVE
        USING      (branch_id IS NULL OR branch_id = ANY (app_branch_scope()))
        WITH CHECK (branch_id IS NULL OR branch_id = ANY (app_branch_scope()))
    $f$, t);
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- `encounters` CITES A TEMPLATE AND A VERSION THAT MAY BE PLATFORM ROWS, AND
-- NEITHER POINTER CAN BE COMPOSITE-FK'D.
--
-- ⚠️ THIS IS WHY THE COMPOSITE FK IS ABSENT, AND IT IS NOT AN OVERSIGHT. A
--   composite (organization_id, template_id) reference would make a PLATFORM
--   template uncitable: the encounter's organization_id is NOT NULL, so both
--   columns are non-null, so the FK would demand a template belonging to the
--   clinic — and the platform's GENERAL template is exactly what a doctor with
--   no classification resolves to. The constraint would refuse the most
--   ordinary consultation on the platform.
--
--   What replaces it is this RESTRICTIVE policy, the same shape
--   `specialty_visible` has on `consultation_templates` and `product_visible`
--   has on `batches`. Without it a clinic could cite ANOTHER TENANT'S private
--   template and read its name and its definition back out of the join.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS template_visible ON encounters;
CREATE POLICY template_visible ON encounters AS RESTRICTIVE
  USING (
    EXISTS (
      SELECT 1 FROM consultation_templates t
      WHERE t.id = encounters.template_id
        AND (t.organization_id IS NULL OR t.organization_id = app_current_org())
    )
    AND EXISTS (
      SELECT 1 FROM consultation_template_versions v
      WHERE v.id = encounters.template_version_id
        AND (v.organization_id IS NULL OR v.organization_id = app_current_org())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM consultation_templates t
      WHERE t.id = encounters.template_id
        AND (t.organization_id IS NULL OR t.organization_id = app_current_org())
    )
    AND EXISTS (
      SELECT 1 FROM consultation_template_versions v
      WHERE v.id = encounters.template_version_id
        AND (v.organization_id IS NULL OR v.organization_id = app_current_org())
    )
  );

-- ---------------------------------------------------------------------------
-- Grants. Ordinary CRUD: a DRAFT is edited in place by the autosave until it is
-- finalized, and immutability after that is enforced by the service and by
-- `encounters_lifecycle_facts`, not by withholding UPDATE.
--
-- DELETE is granted for the same reason it is everywhere else — the soft-delete
-- column is what the application uses, and an organization CASCADE needs it.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  "encounters",
  "encounter_sections"
TO rcln_app;
