/**
 * `InvoiceDocumentData` → one self-contained HTML document.
 *
 * ⚠️ THIS FUNCTION IS THE GUARANTEE. The screen and the PDF are the same
 *   document because they are the same string: `apps/web` puts the return value
 *   in an `<iframe srcdoc>`, the worker hands it to Chromium's `setContent`, and
 *   there is no third path. Anything that renders an invoice by another route —
 *   a React component mounted into the app's own DOM, a second stylesheet, a
 *   "quick" summary card built from the same fields — is a second document that
 *   merely looks like this one, and it will drift on the day somebody edits one
 *   of them.
 *
 * ⚠️ AND IT IS SELF-CONTAINED IN THE STRICT SENSE: not one external request.
 *   No stylesheet link, no font URL, no image, no script. Two reasons, and the
 *   second is the one that bites.
 *
 *     1. `page.pdf()` snapshots what is painted. A font still in flight is a
 *        page rendered in the fallback, and it fails silently — the PDF is
 *        produced, it is just set in the wrong typeface.
 *     2. An `srcdoc` iframe and a `setContent` page resolve relative URLs
 *        against different bases, and in `apps/web` a CSP would refuse them
 *        outright. A document that reached for anything would work in one of
 *        the two renderings and not the other, which is the failure this whole
 *        design exists to make impossible.
 *
 * ⚠️ THE VERSION BELOW IS PROVENANCE, NOT A FEATURE FLAG. It is recorded on
 *   `invoice_documents` so that the question "what did the document this patient
 *   is holding actually look like?" has an answer in three years. It is NOT an
 *   input: an issued invoice's PDF is generated once and never regenerated, so
 *   nothing reads this back to choose a renderer. Bump it whenever the rendered
 *   output changes in a way a reader would notice.
 */

import { renderToStaticMarkup } from 'react-dom/server';

import { fontFaceCss } from '../fonts.js';

import { InvoiceDocument } from './document.js';
import { invoiceStylesheet } from './styles.js';
import type { InvoiceDocumentData } from './types.js';

/** Which template. A second document type gets its own key, not a version. */
export const INVOICE_TEMPLATE_KEY = 'invoice';

/**
 * Bump on any change a reader would notice. See the header.
 *
 * 2 — the line table became per-source (`items.tsx`): a consultation drops the
 *     HSN/SAC and Qty columns and calls its money column "Fee", and every
 *     invoice now names the clinician who provided the care.
 */
export const INVOICE_TEMPLATE_VERSION = 2;

export interface RenderInvoiceOptions {
  /**
   * Leave the typefaces out.
   *
   * Only for tests, which would otherwise carry 141KB of base64 through every
   * assertion and every snapshot diff. ⚠️ Never true in the API, the worker or
   * the web — a document rendered without its fonts is the exact silent drift
   * described above.
   */
  omitFonts?: boolean;
}

export function renderInvoiceHtml(
  data: InvoiceDocumentData,
  options: RenderInvoiceOptions = {}
): string {
  const css = invoiceStylesheet({
    fontFaces: options.omitFonts === true ? '' : fontFaceCss(),
  });

  const body = renderToStaticMarkup(<InvoiceDocument data={data} />);

  /*
   * ⚠️ THE TITLE IS THE INVOICE NUMBER AND NEVER THE PATIENT'S NAME. It becomes
   *   the PDF's document title, the browser tab, and the default filename a
   *   "save as" dialog offers — three places a name would travel to that nobody
   *   thinks of as storage. Same rule as `StoreDocumentInput.fileName`.
   */
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(data.invoiceNumber ?? 'Draft invoice')}</title>
<style>
${css}
</style>
</head>
<body>
${body}
</body>
</html>
`;
}

/**
 * The invoice number is the only value interpolated outside React, which escapes
 * everything else it renders. It is generated by `issueNumber()` and cannot
 * contain any of these — this is here so that stays true if the format changes.
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
