-- ===========================================================================
-- CE-2 — consultation templates and their versions.
--
--   consultation_templates          the IDENTITY: "our dentistry consultation",
--                                   attached to a care context and optionally to
--                                   a node beneath it
--   consultation_template_versions  the DOCUMENT, and there are many
--
-- ⚠️ BOTH ARE PLATFORM-EXTENSIBLE, WITH `specialties`' POLICY AND NOT `files`'.
--   The platform ships a GENERAL consultation per care context so that a clinic
--   can consult on the day it opens; a clinic writes its own beside it and
--   overrides nothing. `files` permits a NULL organization_id in its WITH CHECK,
--   which is right for an asset the platform uploads on a tenant's behalf —
--   reproducing it here would let ANY CLINIC PUBLISH A PLATFORM-WIDE
--   CONSULTATION TEMPLATE, visible to every other tenant on the platform.
--
-- ⚠️ ONE MIGRATION, AND UNLIKE EVERY CE-1 MIGRATION IT NEEDS NO SPLIT.
--   `ConsultationTemplateStatus` is a BRAND-NEW type rather than an
--   `ALTER TYPE … ADD VALUE`, so the CHECK constraints below may name its
--   members in the same transaction that creates it. That is the whole reason
--   CD-9's enum trap does not apply here.
--
-- Generated by `prisma migrate diff`, then extended by hand. The hand-written
-- half starts where it says so.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "ConsultationTemplateStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'RETIRED');

-- CreateTable
CREATE TABLE "consultation_templates" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "code" VARCHAR(64) NOT NULL,
    "name" VARCHAR(160) NOT NULL,
    "description" TEXT,
    "care_context_id" UUID NOT NULL,
    "specialty_id" UUID,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "consultation_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consultation_template_versions" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "template_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "definition" JSONB NOT NULL,
    "status" "ConsultationTemplateStatus" NOT NULL DEFAULT 'DRAFT',
    "published_at" TIMESTAMPTZ(6),
    "published_by" UUID,
    "retired_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "consultation_template_versions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "consultation_templates_organization_id_care_context_id_is_a_idx" ON "consultation_templates"("organization_id", "care_context_id", "is_active");

-- CreateIndex
CREATE INDEX "consultation_templates_organization_id_specialty_id_idx" ON "consultation_templates"("organization_id", "specialty_id");

-- CreateIndex
CREATE UNIQUE INDEX "consultation_templates_organization_id_code_key" ON "consultation_templates"("organization_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "consultation_templates_organization_id_id_key" ON "consultation_templates"("organization_id", "id");

-- CreateIndex
CREATE INDEX "consultation_template_versions_organization_id_template_id__idx" ON "consultation_template_versions"("organization_id", "template_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "consultation_template_versions_organization_id_template_id__key" ON "consultation_template_versions"("organization_id", "template_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "consultation_template_versions_organization_id_id_key" ON "consultation_template_versions"("organization_id", "id");

-- AddForeignKey
ALTER TABLE "consultation_templates" ADD CONSTRAINT "consultation_templates_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consultation_templates" ADD CONSTRAINT "consultation_templates_care_context_id_fkey" FOREIGN KEY ("care_context_id") REFERENCES "specialties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consultation_templates" ADD CONSTRAINT "consultation_templates_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consultation_template_versions" ADD CONSTRAINT "consultation_template_versions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consultation_template_versions" ADD CONSTRAINT "consultation_template_versions_organization_id_template_id_fkey" FOREIGN KEY ("organization_id", "template_id") REFERENCES "consultation_templates"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "consultation_template_versions" ADD CONSTRAINT "consultation_template_versions_published_by_fkey" FOREIGN KEY ("published_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- ===========================================================================
-- HAND-WRITTEN FROM HERE DOWN. Prisma Migrate can express none of it.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- NULLS NOT DISTINCT on both BUSINESS keys.
--
-- Both contain `organization_id`, which is NULL on a platform row. Under
-- Postgres's default NULLS DISTINCT two rows with a NULL organization_id are
-- unique against each other WHATEVER the other columns say — so the platform
-- templates would not be unique against themselves, and the seed's `findFirst`
-- would silently start creating a second GENERAL_HUMAN on its second run.
--
-- ⚠️ THE `(organization_id, id)` COMPOSITE-FK TARGETS ARE DELIBERATELY LEFT
--   ALONE, exactly as the clinical masters left theirs. `id` is the primary key,
--   so that index is already unique on its own whatever NULLs the first column
--   holds — and the rewrite would FAIL anyway, because Postgres refuses to drop
--   an index a foreign key depends on.
-- ---------------------------------------------------------------------------
DROP INDEX "consultation_templates_organization_id_code_key";
CREATE UNIQUE INDEX "consultation_templates_organization_id_code_key"
  ON "consultation_templates" ("organization_id", "code") NULLS NOT DISTINCT;

DROP INDEX "consultation_template_versions_organization_id_template_id__key";
CREATE UNIQUE INDEX "consultation_template_versions_organization_id_template_id__key"
  ON "consultation_template_versions" ("organization_id", "template_id", "version")
  NULLS NOT DISTINCT;

-- ---------------------------------------------------------------------------
-- ONE ACTIVE TEMPLATE PER NODE. The index that makes resolution a DECISION.
--
-- ⚠️ WITHOUT THIS, RESOLUTION HAS A TIE TO BREAK AND NOBODY EVER SEES IT. Two
--   active templates on the same node both apply equally; the resolver's
--   tie-break picks one, the other is configured, visible in the admin screen
--   and inert, and the consultation that renders is perfectly reasonable and not
--   the one the clinic meant. There is no error and nothing on screen to notice
--   — the same failure `mostSpecific` in @rcln/regulatory was written to prevent.
--
-- Prisma cannot express `WHERE is_active AND deleted_at IS NULL`, and NULLS NOT
-- DISTINCT is needed twice over: `organization_id` is NULL for a platform row
-- and `specialty_id` is NULL for the care-context default, which is precisely
-- the row that must be unique.
--
-- ⚠️ A CLINIC'S OWN TEMPLATE AND THE PLATFORM'S AT THE SAME NODE ARE STILL TWO
--   LEGAL ROWS — they differ in organization_id. That overlap is the whole point
--   of a platform-extensible catalogue, and it is settled in `resolveTemplate`,
--   which prefers the clinic's own. This index only forbids a clinic colliding
--   with ITSELF.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "consultation_templates_one_active_per_node"
  ON "consultation_templates" ("organization_id", "care_context_id", "specialty_id")
  NULLS NOT DISTINCT
  WHERE "is_active" AND "deleted_at" IS NULL;

-- ---------------------------------------------------------------------------
-- AT MOST ONE DRAFT PER TEMPLATE.
--
-- Two open drafts is two people editing the same configuration with no idea the
-- other exists, and whichever publishes second silently discards the first —
-- there is no merge, because a definition is one document.
--
-- ⚠️ AND AT MOST ONE PUBLISHED VERSION PER TEMPLATE, which is the stronger of
--   the two claims. `resolveTemplate` takes the published version of each
--   candidate; two of them would mean the applied configuration depends on which
--   row the planner returned first. Publishing RETIRES the previous version in
--   the same transaction, and this index is what stops a writer that forgets.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "consultation_template_versions_one_draft"
  ON "consultation_template_versions" ("organization_id", "template_id") NULLS NOT DISTINCT
  WHERE "status" = 'DRAFT';

CREATE UNIQUE INDEX "consultation_template_versions_one_published"
  ON "consultation_template_versions" ("organization_id", "template_id") NULLS NOT DISTINCT
  WHERE "status" = 'PUBLISHED';

-- ---------------------------------------------------------------------------
-- A PUBLISHED VERSION CARRIES ITS PUBLICATION FACTS; A DRAFT CARRIES NONE.
--
-- ⚠️ `published_at` ON A DRAFT IS THE BUG THIS REFUSES. A version that is DRAFT
--   and has a publication date reads as live in every report and in every screen
--   that renders "published on…", while resolving to nothing — and it is exactly
--   what a half-finished publish leaves behind if the transaction is written in
--   the wrong order.
--
-- Legal because `ConsultationTemplateStatus` is a BRAND-NEW type created in this
-- same migration rather than an `ALTER TYPE … ADD VALUE` (CD-9).
-- ---------------------------------------------------------------------------
ALTER TABLE "consultation_template_versions"
  ADD CONSTRAINT "consultation_template_versions_published_facts"
  CHECK (
    ("status" = 'DRAFT'     AND "published_at" IS NULL     AND "retired_at" IS NULL)
    OR ("status" = 'PUBLISHED' AND "published_at" IS NOT NULL AND "retired_at" IS NULL)
    -- ⚠️ A RETIRED VERSION WAS NECESSARILY PUBLISHED FIRST. Retirement is what
    --   happens to a live configuration when the next one goes live; a draft
    --   nobody wants is deleted, because it was never a statement about how
    --   consultations are conducted and no encounter can cite it.
    OR ("status" = 'RETIRED'   AND "published_at" IS NOT NULL AND "retired_at" IS NOT NULL)
  );

-- `version` is issued by the service and is monotonic per template. Zero and
-- negatives are not a version anybody can cite.
ALTER TABLE "consultation_template_versions"
  ADD CONSTRAINT "consultation_template_versions_version_positive"
  CHECK ("version" >= 1);

-- ---------------------------------------------------------------------------
-- RLS — platform-extensible, read permissive, write strict.
--
-- ⚠️ THIS IS THE `specialties` POLICY, NOT THE `files` POLICY, AND THE
--   DIFFERENCE IS A CROSS-TENANT WRITE. See the header, and the full reasoning
--   in `rls/enable-rls.sql`; it is not repeated here.
--
-- The `platform_rows_immutable` trigger closes the two holes the policy cannot:
-- a DELETE of a platform row (Postgres applies no WITH CHECK to DELETE, so USING
-- is the whole test and USING permits NULL), and CAPTURE by an UPDATE that sets
-- organization_id to the caller's own.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  platform_extensible text[] := ARRAY[
    'consultation_templates',
    'consultation_template_versions'
  ];
BEGIN
  FOREACH t IN ARRAY platform_extensible LOOP
    EXECUTE format('ALTER TABLE %I ENABLE   ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING      (organization_id IS NULL OR organization_id = app_current_org())
        WITH CHECK (organization_id = app_current_org())
    $f$, t);

    EXECUTE format('DROP TRIGGER IF EXISTS platform_rows_immutable ON %I', t);
    EXECUTE format($f$
      CREATE TRIGGER platform_rows_immutable
        BEFORE UPDATE OR DELETE ON %I
        FOR EACH ROW EXECUTE FUNCTION refuse_platform_row_mutation()
    $f$, t);
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- `consultation_templates` POINTS AT `specialties` TWICE, AND NEITHER POINTER
-- CAN BE COMPOSITE-FK'D.
--
-- `specialties` allows a NULL organization_id, so there is no
-- (organization_id, id) pair to compose with for a platform node — which means
-- `tenant_isolation` constrains the TEMPLATE row and says nothing at all about
-- the two nodes it cites. Without this, a tenant could attach its own template
-- to ANOTHER TENANT'S private specialty and read that specialty's name back out
-- of the join.
--
-- Identical shape and reasoning to `specialty_visible` on
-- `clinical_master_scopes` and on `doctor_specialties`. RESTRICTIVE so it ANDs
-- with tenant_isolation rather than widening it.
--
-- ⚠️ `specialty_id` IS NULLABLE AND A NULL MUST PASS — it is the care-context
--   default, the one template that must always resolve. `IS NULL OR EXISTS(…)`,
--   as `clinical_episodes.primary_specialty_id` does.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS specialty_visible ON consultation_templates;
CREATE POLICY specialty_visible ON consultation_templates AS RESTRICTIVE
  USING (
    EXISTS (
      SELECT 1 FROM specialties s
      WHERE s.id = consultation_templates.care_context_id
        AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
    )
    AND (
      consultation_templates.specialty_id IS NULL
      OR EXISTS (
        SELECT 1 FROM specialties s
        WHERE s.id = consultation_templates.specialty_id
          AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
      )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM specialties s
      WHERE s.id = consultation_templates.care_context_id
        AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
    )
    AND (
      consultation_templates.specialty_id IS NULL
      OR EXISTS (
        SELECT 1 FROM specialties s
        WHERE s.id = consultation_templates.specialty_id
          AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Grants. `rcln_app` gets ordinary CRUD; nothing here is append-only, because a
-- DRAFT is edited in place until it is published.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  "consultation_templates",
  "consultation_template_versions"
TO rcln_app;
