-- ===========================================================================
-- CE-1 · 2 of 4 — the clinical vocabulary, and the care subject.
--
-- Four platform-extensible tables plus one thin org-scoped one:
--
--   clinical_master_items      every clinical WORD, one table, `kind` discriminator
--   clinical_master_codings    ICD-10 / SNOMED / LOINC / a clinic's own, all at once
--   clinical_master_scopes     which taxonomy nodes a word is relevant to
--   product_clinical_scopes    the same, for the medicine catalogue
--   animal_profiles            species/breed/weight, when the patient is not a person
--
-- ⚠️ THE FOUR SCOPE/MASTER TABLES ARE PLATFORM-EXTENSIBLE, `animal_profiles` IS
--   NOT. "Tooth pain" and "Dental caries" are WORDS — every clinic needs the
--   same few hundred on the day it opens, and shipping them as platform rows is
--   what lets a dentist record a first consultation without inventing a
--   vocabulary first. The same argument `stock_reason_codes` makes. An animal's
--   weight is a fact about one clinic's patient and is never platform data.
--
-- Generated by `prisma migrate diff`, then split and extended by hand. The
-- hand-written half starts where it says so.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "ClinicalMasterKind" AS ENUM ('SYMPTOM', 'DIAGNOSIS', 'PROCEDURE', 'INVESTIGATION', 'ADVICE', 'HISTORY_ITEM', 'FINDING_TYPE');

-- CreateEnum
CREATE TYPE "CareSubjectType" AS ENUM ('HUMAN', 'ANIMAL');

-- AlterTable
-- ⚠️ DEFAULT 'HUMAN', so every row written before this column existed is correct
--   without a backfill and without a rewrite of the table.
ALTER TABLE "patients" ADD COLUMN     "subject_type" "CareSubjectType" NOT NULL DEFAULT 'HUMAN';

-- CreateTable
CREATE TABLE "clinical_master_items" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "kind" "ClinicalMasterKind" NOT NULL,
    "parent_id" UUID,
    "code" VARCHAR(64) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "metadata" JSONB,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "clinical_master_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clinical_master_codings" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "item_id" UUID NOT NULL,
    "system" VARCHAR(32) NOT NULL,
    "code" VARCHAR(64) NOT NULL,
    "display" VARCHAR(512),
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "clinical_master_codings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clinical_master_scopes" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "item_id" UUID NOT NULL,
    "specialty_id" UUID NOT NULL,
    "relevance" SMALLINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "clinical_master_scopes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_clinical_scopes" (
    "id" UUID NOT NULL,
    "organization_id" UUID,
    "product_id" UUID NOT NULL,
    "specialty_id" UUID NOT NULL,
    "relevance" SMALLINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_clinical_scopes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "animal_profiles" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "patient_id" UUID NOT NULL,
    "species" VARCHAR(64),
    "breed" VARCHAR(128),
    "weight_kg" DECIMAL(8,3),
    "guardian_name" VARCHAR(255),
    "guardian_phone" VARCHAR(20),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "animal_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "clinical_master_items_organization_id_kind_is_active_idx" ON "clinical_master_items"("organization_id", "kind", "is_active");

-- CreateIndex
CREATE INDEX "clinical_master_items_parent_id_idx" ON "clinical_master_items"("parent_id");

-- CreateIndex
CREATE UNIQUE INDEX "clinical_master_items_organization_id_kind_code_key" ON "clinical_master_items"("organization_id", "kind", "code");

-- CreateIndex
CREATE UNIQUE INDEX "clinical_master_items_organization_id_id_key" ON "clinical_master_items"("organization_id", "id");

-- CreateIndex
CREATE INDEX "clinical_master_codings_organization_id_system_code_idx" ON "clinical_master_codings"("organization_id", "system", "code");

-- CreateIndex
CREATE UNIQUE INDEX "clinical_master_codings_organization_id_item_id_system_code_key" ON "clinical_master_codings"("organization_id", "item_id", "system", "code");

-- CreateIndex
CREATE INDEX "clinical_master_scopes_organization_id_specialty_id_idx" ON "clinical_master_scopes"("organization_id", "specialty_id");

-- CreateIndex
CREATE UNIQUE INDEX "clinical_master_scopes_organization_id_item_id_specialty_id_key" ON "clinical_master_scopes"("organization_id", "item_id", "specialty_id");

-- CreateIndex
CREATE INDEX "product_clinical_scopes_organization_id_specialty_id_idx" ON "product_clinical_scopes"("organization_id", "specialty_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_clinical_scopes_organization_id_product_id_specialt_key" ON "product_clinical_scopes"("organization_id", "product_id", "specialty_id");

-- CreateIndex
CREATE UNIQUE INDEX "animal_profiles_organization_id_patient_id_key" ON "animal_profiles"("organization_id", "patient_id");

-- AddForeignKey
ALTER TABLE "clinical_master_items" ADD CONSTRAINT "clinical_master_items_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_items" ADD CONSTRAINT "clinical_master_items_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_codings" ADD CONSTRAINT "clinical_master_codings_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_codings" ADD CONSTRAINT "clinical_master_codings_organization_id_item_id_fkey" FOREIGN KEY ("organization_id", "item_id") REFERENCES "clinical_master_items"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_scopes" ADD CONSTRAINT "clinical_master_scopes_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_scopes" ADD CONSTRAINT "clinical_master_scopes_organization_id_item_id_fkey" FOREIGN KEY ("organization_id", "item_id") REFERENCES "clinical_master_items"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clinical_master_scopes" ADD CONSTRAINT "clinical_master_scopes_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_clinical_scopes" ADD CONSTRAINT "product_clinical_scopes_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_clinical_scopes" ADD CONSTRAINT "product_clinical_scopes_organization_id_product_id_fkey" FOREIGN KEY ("organization_id", "product_id") REFERENCES "products"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_clinical_scopes" ADD CONSTRAINT "product_clinical_scopes_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "animal_profiles" ADD CONSTRAINT "animal_profiles_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "animal_profiles" ADD CONSTRAINT "animal_profiles_organization_id_patient_id_fkey" FOREIGN KEY ("organization_id", "patient_id") REFERENCES "patients"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- HAND-WRITTEN FROM HERE DOWN. Prisma Migrate can express none of it.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- NULLS NOT DISTINCT on the four BUSINESS keys.
--
-- Every one contains `organization_id`, which is NULL on a platform row. Under
-- Postgres's default NULLS DISTINCT two rows with a NULL organization_id are
-- unique against each other WHATEVER the other columns say — so the platform
-- vocabulary would not be unique against itself, and the seed's `findFirst`
-- would silently start creating duplicate diagnoses on its second run.
--
-- ⚠️ THE `(organization_id, id)` COMPOSITE-FK TARGET IS DELIBERATELY LEFT ALONE,
--   exactly as the product catalogue left its own. `id` is the primary key, so
--   that index is already unique on its own whatever NULLs the first column
--   holds — and the rewrite would FAIL anyway, because Postgres refuses to drop
--   an index a foreign key depends on.
--
-- Each is dropped and recreated under Prisma's own generated name, so a future
-- `migrate dev` does not propose to recreate it.
-- ---------------------------------------------------------------------------
DROP INDEX "clinical_master_items_organization_id_kind_code_key";
CREATE UNIQUE INDEX "clinical_master_items_organization_id_kind_code_key"
  ON "clinical_master_items" ("organization_id", "kind", "code") NULLS NOT DISTINCT;

DROP INDEX "clinical_master_codings_organization_id_item_id_system_code_key";
CREATE UNIQUE INDEX "clinical_master_codings_organization_id_item_id_system_code_key"
  ON "clinical_master_codings" ("organization_id", "item_id", "system", "code") NULLS NOT DISTINCT;

DROP INDEX "clinical_master_scopes_organization_id_item_id_specialty_id_key";
CREATE UNIQUE INDEX "clinical_master_scopes_organization_id_item_id_specialty_id_key"
  ON "clinical_master_scopes" ("organization_id", "item_id", "specialty_id") NULLS NOT DISTINCT;

DROP INDEX "product_clinical_scopes_organization_id_product_id_specialt_key";
CREATE UNIQUE INDEX "product_clinical_scopes_organization_id_product_id_specialt_key"
  ON "product_clinical_scopes" ("organization_id", "product_id", "specialty_id") NULLS NOT DISTINCT;

-- ---------------------------------------------------------------------------
-- At most one PRIMARY coding per (item, system).
--
-- Prisma cannot express `WHERE is_primary`. Without this a clinic can nominate
-- two different ICD-10 codes as the one to print on a report, and which one
-- appears is then whatever the planner felt like.
--
-- ⚠️ PER SYSTEM, NOT PER ITEM. One diagnosis legitimately has a primary ICD-10
--   code AND a primary SNOMED code; those are answers to different questions.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "clinical_master_codings_one_primary"
  ON "clinical_master_codings" ("organization_id", "item_id", "system") NULLS NOT DISTINCT
  WHERE "is_primary";

-- ---------------------------------------------------------------------------
-- The clinical selector's search index.
--
-- ⚠️ A GIN TRIGRAM INDEX OVER AN EXPRESSION, WHICH PRISMA CAN NEITHER EXPRESS
--   NOR SEE. Because it cannot see it, it will never propose to drop it — the
--   opposite of the plain-column trigram index on `patients.phone`, which
--   Prisma DID offer to drop until it was declared in the schema.
--
--   Without it, every keystroke in every clinical selector is a sequential scan
--   over every word on the PLATFORM — filtered by RLS afterwards, so the cost
--   grows with the platform and not with the tenant. This is the exact failure
--   `patients` documented, and the selectors here are typed into far more often
--   than a patient search is.
--
-- `pg_trgm` is already installed by an earlier migration.
-- ---------------------------------------------------------------------------
CREATE INDEX "clinical_master_items_name_trgm_idx"
  ON "clinical_master_items" USING GIN (lower("name") gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- RLS — platform-extensible, read permissive, write strict.
--
-- ⚠️ THIS IS THE `specialties` POLICY, NOT THE `files` POLICY, AND THE
--   DIFFERENCE IS A CROSS-TENANT WRITE. `files` permits a NULL organization_id
--   in its WITH CHECK, which is right for an asset the platform uploads on a
--   tenant's behalf. Reproducing it here would let ANY CLINIC INSERT A
--   PLATFORM-WIDE DIAGNOSIS — a row with organization_id NULL, instantly
--   visible to every other tenant on the platform, writable by anyone holding
--   `clinical.master.manage`.
--
-- The `platform_rows_immutable` trigger closes the two holes the policy cannot:
-- a DELETE of a platform row (Postgres applies no WITH CHECK to DELETE, so
-- USING is the whole test and USING permits NULL), and CAPTURE by an UPDATE
-- that sets organization_id to the caller's own. See the full reasoning in
-- `rls/enable-rls.sql`; it is not repeated here.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  platform_extensible text[] := ARRAY[
    'clinical_master_items',
    'clinical_master_codings',
    'clinical_master_scopes',
    'product_clinical_scopes'
  ];
BEGIN
  FOREACH t IN ARRAY platform_extensible LOOP
    EXECUTE format('ALTER TABLE %I ENABLE   ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING      (organization_id IS NULL OR organization_id = app_current_org())
        WITH CHECK (organization_id = app_current_org())
    $f$, t);

    EXECUTE format('DROP TRIGGER IF EXISTS platform_rows_immutable ON %I', t);
    EXECUTE format($f$
      CREATE TRIGGER platform_rows_immutable
        BEFORE UPDATE OR DELETE ON %I
        FOR EACH ROW EXECUTE FUNCTION refuse_platform_row_mutation()
    $f$, t);
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- Both scope tables point at TWO parents and only one is composite-FK'd.
--
-- `specialty_id` is a PLAIN FK to `specialties(id)`, because a specialty may be
-- a platform row with no organization_id to compose with. `tenant_isolation`
-- therefore constrains the ITEM/PRODUCT side and says nothing at all about the
-- SPECIALTY side — without this, a tenant could scope its own diagnosis to
-- ANOTHER TENANT'S private specialty and read that specialty's name back out of
-- the join.
--
-- Identical shape and reasoning to `specialty_visible` on `doctor_specialties`.
-- RESTRICTIVE so it ANDs with tenant_isolation rather than widening it.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS specialty_visible ON clinical_master_scopes;
CREATE POLICY specialty_visible ON clinical_master_scopes AS RESTRICTIVE
  USING (EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = clinical_master_scopes.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = clinical_master_scopes.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ));

DROP POLICY IF EXISTS specialty_visible ON product_clinical_scopes;
CREATE POLICY specialty_visible ON product_clinical_scopes AS RESTRICTIVE
  USING (EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = product_clinical_scopes.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = product_clinical_scopes.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ));

-- ---------------------------------------------------------------------------
-- `product_clinical_scopes.product_id` is composite-FK'd to
-- `products(organization_id, id)`, so a tenant cannot cite another tenant's
-- product — but under MATCH SIMPLE that constraint is NOT CHECKED AT ALL when
-- organization_id is NULL, which is exactly the platform case. A restrictive
-- product predicate closes it, as `batches.product_visible` does.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS product_visible ON product_clinical_scopes;
CREATE POLICY product_visible ON product_clinical_scopes AS RESTRICTIVE
  USING (EXISTS (
    SELECT 1 FROM products p
    WHERE p.id = product_clinical_scopes.product_id
      AND (p.organization_id IS NULL OR p.organization_id = app_current_org())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM products p
    WHERE p.id = product_clinical_scopes.product_id
      AND (p.organization_id IS NULL OR p.organization_id = app_current_org())
  ));

-- ---------------------------------------------------------------------------
-- `animal_profiles` is ORDINARY TENANT DATA — org-scoped, no branch. An animal
-- is a patient, and `patients` is deliberately org-wide (ADR-0016): the record
-- follows the subject into whichever branch it walks into.
-- ---------------------------------------------------------------------------
ALTER TABLE "animal_profiles" ENABLE   ROW LEVEL SECURITY;
ALTER TABLE "animal_profiles" NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON animal_profiles;
CREATE POLICY tenant_isolation ON animal_profiles
  USING      (organization_id = app_current_org())
  WITH CHECK (organization_id = app_current_org());

-- ---------------------------------------------------------------------------
-- Grants. `rcln_app` gets ordinary CRUD; nothing here is append-only.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  "clinical_master_items",
  "clinical_master_codings",
  "clinical_master_scopes",
  "product_clinical_scopes",
  "animal_profiles"
TO rcln_app;
