-- ===========================================================================
-- CE-4 · 2 of 2 — the eight clinical content tables.
--
--   encounter_symptoms        encounter_diagnoses      encounter_procedures
--   encounter_prescriptions   encounter_investigations encounter_advice
--   encounter_referrals       encounter_attachments
--
-- ALL EIGHT ARE ORG + BRANCH SCOPED AND ALL EIGHT ARE PHI.
--
-- ⚠️ ELEVEN BRAND-NEW ENUM TYPES, SO THE CHECK CONSTRAINTS BELOW MAY NAME
--   THEIR MEMBERS IN THIS SAME TRANSACTION (CD-9). The one
--   `ALTER TYPE … ADD VALUE` this phase needs — `DocumentType.CLINICAL_ATTACHMENT`
--   — is migration 1 and is deliberately not here.
--
-- ⚠️ EVERY TABLE CARRIES `organization_id` AND `branch_id` ITSELF rather than
--   inheriting through its encounter. A child of a branch-scoped parent that
--   inherits only the org half is the hole `appointment_status_history` had to
--   restate by hand: the org policy passes and the branch boundary is simply
--   not there. The composite FK to `(organization_id, encounter_id)` is what
--   stops the two columns disagreeing with the consultation they belong to.
--
-- ⚠️ FIVE OF THEM POINT AT `clinical_master_items`, ONE AT `products` AND ONE
--   AT `specialties`, AND NONE OF THOSE POINTERS CAN BE A COMPOSITE FK. All
--   three parents allow a NULL `organization_id`; these rows' is NOT NULL, so
--   the constraint would refuse the entire platform catalogue — the same
--   situation `encounters.template_id` is in. `item_visible`,
--   `product_visible` and `specialty_visible` at the bottom of this file are
--   what stand in for it, and without them a clinic can cite another tenant's
--   private word and read its name back out of the join.
--
-- Generated by `prisma migrate diff`, then extended by hand. The hand-written
-- half starts where it says so.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "ClinicalSeverity" AS ENUM ('MILD', 'MODERATE', 'SEVERE');

-- CreateEnum
CREATE TYPE "DiagnosisRole" AS ENUM ('PRIMARY', 'SECONDARY', 'DIFFERENTIAL');

-- CreateEnum
CREATE TYPE "DiagnosisCertainty" AS ENUM ('CONFIRMED', 'PROVISIONAL', 'SUSPECTED', 'RULED_OUT');

-- CreateEnum
CREATE TYPE "EncounterProcedureStatus" AS ENUM ('PLANNED', 'PERFORMED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "InvestigationPriority" AS ENUM ('ROUTINE', 'URGENT', 'STAT');

-- CreateEnum
CREATE TYPE "InvestigationStatus" AS ENUM ('ORDERED', 'COLLECTED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ReferralUrgency" AS ENUM ('ROUTINE', 'URGENT', 'EMERGENCY');

-- CreateEnum
CREATE TYPE "MedicationRoute" AS ENUM ('ORAL', 'TOPICAL', 'INTRAVENOUS', 'INTRAMUSCULAR', 'SUBCUTANEOUS', 'INHALATION', 'OPHTHALMIC', 'OTIC', 'NASAL', 'RECTAL', 'VAGINAL', 'SUBLINGUAL', 'TRANSDERMAL', 'OTHER');

-- CreateEnum
CREATE TYPE "MedicationFrequencyUnit" AS ENUM ('DAY', 'WEEK', 'MONTH');

-- CreateEnum
CREATE TYPE "MedicationFoodRelation" AS ENUM ('BEFORE_FOOD', 'AFTER_FOOD', 'WITH_FOOD', 'ANY');

-- CreateEnum
CREATE TYPE "EncounterAttachmentKind" AS ENUM ('PHOTO', 'REPORT', 'SCAN', 'CONSENT', 'LETTER', 'OTHER');

-- CreateTable
CREATE TABLE "encounter_symptoms" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "item_id" UUID,
    "custom_text" VARCHAR(255),
    "duration_value" SMALLINT,
    "duration_unit" "ClinicalDurationUnit",
    "severity" "ClinicalSeverity",
    "frequency" VARCHAR(120),
    "site" VARCHAR(120),
    "notes" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_symptoms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_diagnoses" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "item_id" UUID,
    "custom_text" VARCHAR(255),
    "role" "DiagnosisRole" NOT NULL DEFAULT 'SECONDARY',
    "certainty" "DiagnosisCertainty" NOT NULL DEFAULT 'PROVISIONAL',
    "notes" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_diagnoses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_procedures" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "item_id" UUID,
    "diagnosis_id" UUID,
    "performed_on" DATE,
    "status" "EncounterProcedureStatus" NOT NULL DEFAULT 'PLANNED',
    "notes" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_procedures_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_prescriptions" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "strength" VARCHAR(64),
    "dose" DECIMAL(10,3),
    "dose_unit" VARCHAR(32),
    "route" "MedicationRoute",
    "frequency" SMALLINT,
    "frequency_unit" "MedicationFrequencyUnit",
    "duration_value" SMALLINT,
    "duration_unit" "ClinicalDurationUnit",
    "food_relation" "MedicationFoodRelation",
    "timing" VARCHAR(120),
    "quantity" DECIMAL(12,3),
    "start_date" DATE,
    "end_date" DATE,
    "is_prn" BOOLEAN NOT NULL DEFAULT false,
    "instructions" TEXT,
    "notes" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_prescriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_investigations" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "item_id" UUID,
    "reason" TEXT,
    "priority" "InvestigationPriority" NOT NULL DEFAULT 'ROUTINE',
    "instructions" TEXT,
    "status" "InvestigationStatus" NOT NULL DEFAULT 'ORDERED',
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_investigations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_advice" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "item_id" UUID,
    "custom_text" TEXT,
    "is_edited" BOOLEAN NOT NULL DEFAULT false,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_advice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_referrals" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "specialty_id" UUID,
    "doctor_profile_id" UUID,
    "external_name" VARCHAR(255),
    "reason" TEXT,
    "urgency" "ReferralUrgency" NOT NULL DEFAULT 'ROUTINE',
    "notes" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_referrals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "encounter_attachments" (
    "id" UUID NOT NULL,
    "organization_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "encounter_id" UUID NOT NULL,
    "stored_file_id" UUID NOT NULL,
    "kind" "EncounterAttachmentKind" NOT NULL DEFAULT 'OTHER',
    "caption" VARCHAR(500),
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "encounter_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "encounter_symptoms_organization_id_encounter_id_display_ord_idx" ON "encounter_symptoms"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_symptoms_organization_id_item_id_idx" ON "encounter_symptoms"("organization_id", "item_id");

-- CreateIndex
CREATE INDEX "encounter_diagnoses_organization_id_encounter_id_display_or_idx" ON "encounter_diagnoses"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_diagnoses_organization_id_item_id_idx" ON "encounter_diagnoses"("organization_id", "item_id");

-- CreateIndex
CREATE UNIQUE INDEX "encounter_diagnoses_organization_id_id_key" ON "encounter_diagnoses"("organization_id", "id");

-- CreateIndex
CREATE INDEX "encounter_procedures_organization_id_encounter_id_display_o_idx" ON "encounter_procedures"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_procedures_organization_id_item_id_status_idx" ON "encounter_procedures"("organization_id", "item_id", "status");

-- CreateIndex
CREATE INDEX "encounter_prescriptions_organization_id_encounter_id_displa_idx" ON "encounter_prescriptions"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_prescriptions_organization_id_product_id_idx" ON "encounter_prescriptions"("organization_id", "product_id");

-- CreateIndex
CREATE INDEX "encounter_prescriptions_organization_id_branch_id_created_a_idx" ON "encounter_prescriptions"("organization_id", "branch_id", "created_at");

-- CreateIndex
CREATE INDEX "encounter_investigations_organization_id_encounter_id_displ_idx" ON "encounter_investigations"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_investigations_organization_id_status_created_at_idx" ON "encounter_investigations"("organization_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "encounter_advice_organization_id_encounter_id_display_order_idx" ON "encounter_advice"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_referrals_organization_id_encounter_id_display_or_idx" ON "encounter_referrals"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE INDEX "encounter_attachments_organization_id_encounter_id_display__idx" ON "encounter_attachments"("organization_id", "encounter_id", "display_order");

-- CreateIndex
CREATE UNIQUE INDEX "encounter_attachments_organization_id_encounter_id_stored_f_key" ON "encounter_attachments"("organization_id", "encounter_id", "stored_file_id");

-- AddForeignKey
ALTER TABLE "encounter_symptoms" ADD CONSTRAINT "encounter_symptoms_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_symptoms" ADD CONSTRAINT "encounter_symptoms_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_symptoms" ADD CONSTRAINT "encounter_symptoms_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_symptoms" ADD CONSTRAINT "encounter_symptoms_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_diagnoses" ADD CONSTRAINT "encounter_diagnoses_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_diagnoses" ADD CONSTRAINT "encounter_diagnoses_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_diagnoses" ADD CONSTRAINT "encounter_diagnoses_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_diagnoses" ADD CONSTRAINT "encounter_diagnoses_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_procedures" ADD CONSTRAINT "encounter_procedures_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_procedures" ADD CONSTRAINT "encounter_procedures_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_procedures" ADD CONSTRAINT "encounter_procedures_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_procedures" ADD CONSTRAINT "encounter_procedures_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_procedures" ADD CONSTRAINT "encounter_procedures_organization_id_diagnosis_id_fkey" FOREIGN KEY ("organization_id", "diagnosis_id") REFERENCES "encounter_diagnoses"("organization_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "encounter_prescriptions" ADD CONSTRAINT "encounter_prescriptions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_prescriptions" ADD CONSTRAINT "encounter_prescriptions_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_prescriptions" ADD CONSTRAINT "encounter_prescriptions_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_prescriptions" ADD CONSTRAINT "encounter_prescriptions_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_investigations" ADD CONSTRAINT "encounter_investigations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_investigations" ADD CONSTRAINT "encounter_investigations_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_investigations" ADD CONSTRAINT "encounter_investigations_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_investigations" ADD CONSTRAINT "encounter_investigations_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_advice" ADD CONSTRAINT "encounter_advice_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_advice" ADD CONSTRAINT "encounter_advice_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_advice" ADD CONSTRAINT "encounter_advice_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_advice" ADD CONSTRAINT "encounter_advice_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "clinical_master_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_referrals" ADD CONSTRAINT "encounter_referrals_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_referrals" ADD CONSTRAINT "encounter_referrals_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_referrals" ADD CONSTRAINT "encounter_referrals_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_referrals" ADD CONSTRAINT "encounter_referrals_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_referrals" ADD CONSTRAINT "encounter_referrals_organization_id_doctor_profile_id_fkey" FOREIGN KEY ("organization_id", "doctor_profile_id") REFERENCES "doctor_profiles"("organization_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "encounter_attachments" ADD CONSTRAINT "encounter_attachments_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_attachments" ADD CONSTRAINT "encounter_attachments_organization_id_branch_id_fkey" FOREIGN KEY ("organization_id", "branch_id") REFERENCES "branches"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_attachments" ADD CONSTRAINT "encounter_attachments_organization_id_encounter_id_fkey" FOREIGN KEY ("organization_id", "encounter_id") REFERENCES "encounters"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "encounter_attachments" ADD CONSTRAINT "encounter_attachments_organization_id_stored_file_id_fkey" FOREIGN KEY ("organization_id", "stored_file_id") REFERENCES "files"("organization_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;


-- ===========================================================================
-- THE HAND-WRITTEN HALF. Everything above is `prisma migrate diff`; everything
-- below is what Prisma Migrate cannot express — NOT NULLs it will not infer
-- from an optional relation, CHECK constraints, partial unique indexes, row
-- level security and grants.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- TWO `item_id` COLUMNS ARE REQUIRED, AND PRISMA CANNOT SAY SO.
--
-- A required relation may not include a nullable scalar, and these relations
-- are plain FKs into a platform-extensible table. So the models declare them
-- optional and the database states the truth.
--
-- ⚠️ THE OTHER THREE — SYMPTOMS, DIAGNOSES, ADVICE — ARE GENUINELY NULLABLE,
--   and that is CD-6 and §6 rather than an inconsistency. A clinician must be
--   able to record a symptom the vocabulary has not learned yet, and forcing
--   every free-text entry to create a master row pollutes a SHARED PLATFORM
--   catalogue with one clinic's typos.
--
--   A PROCEDURE and an INVESTIGATION are different: they are billed, consumed
--   from stock (PI-9) and reported on, so a free-text one is a line nothing
--   downstream can price or count.
-- ---------------------------------------------------------------------------
ALTER TABLE "encounter_procedures" ALTER COLUMN "item_id" SET NOT NULL;
ALTER TABLE "encounter_investigations" ALTER COLUMN "item_id" SET NOT NULL;

-- ---------------------------------------------------------------------------
-- CODED OR TYPED, EXACTLY ONE.
--
-- ⚠️ `num_nonnulls(...) = 1` RATHER THAN "AT LEAST ONE". Allowing both would
--   let a custom label sit beside a coded word and silently contradict it —
--   and then every report grouping by `item_id` shows one thing while the
--   chart shows another. A row naming neither is a symptom of nothing.
-- ---------------------------------------------------------------------------
ALTER TABLE "encounter_symptoms"
  ADD CONSTRAINT "encounter_symptoms_coded_or_typed"
  CHECK (num_nonnulls("item_id", "custom_text") = 1);

ALTER TABLE "encounter_diagnoses"
  ADD CONSTRAINT "encounter_diagnoses_coded_or_typed"
  CHECK (num_nonnulls("item_id", "custom_text") = 1);

ALTER TABLE "encounter_advice"
  ADD CONSTRAINT "encounter_advice_coded_or_typed"
  CHECK (num_nonnulls("item_id", "custom_text") = 1);

-- ⚠️ A DURATION OF "3" OF NOTHING IS NOT A DURATION — the same pair rule
--   `encounters.chief_complaint_duration_*` carries, for the same reason.
ALTER TABLE "encounter_symptoms"
  ADD CONSTRAINT "encounter_symptoms_duration_pair"
  CHECK (
    ("duration_value" IS NULL AND "duration_unit" IS NULL)
    OR ("duration_value" IS NOT NULL AND "duration_unit" IS NOT NULL)
  );

ALTER TABLE "encounter_symptoms"
  ADD CONSTRAINT "encounter_symptoms_duration_positive"
  CHECK ("duration_value" IS NULL OR "duration_value" > 0);

-- ---------------------------------------------------------------------------
-- AT MOST ONE PRIMARY DIAGNOSIS PER CONSULTATION.
--
-- Two primaries is two answers to "what was this visit about", and every
-- report that groups by primary diagnosis counts the visit twice. Partial, and
-- therefore hand-written: Prisma cannot express `WHERE role = 'PRIMARY'`.
--
-- SECONDARY and DIFFERENTIAL are deliberately unconstrained — a consultation
-- legitimately carries several of each.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "encounter_diagnoses_one_primary"
  ON "encounter_diagnoses" ("organization_id", "encounter_id")
  WHERE "role" = 'PRIMARY';

-- ---------------------------------------------------------------------------
-- THE DOSING PAIRS, AND THE ONE ORDERING RULE.
--
-- ⚠️ EVERY PAIR TRAVELS TOGETHER OR NOT AT ALL. "Twice per" nothing and "for
--   5" nothing are both prescriptions a pharmacist cannot fill, and both are
--   what a half-completed form produces.
-- ---------------------------------------------------------------------------
ALTER TABLE "encounter_prescriptions"
  ADD CONSTRAINT "encounter_prescriptions_frequency_pair"
  CHECK (
    ("frequency" IS NULL AND "frequency_unit" IS NULL)
    OR ("frequency" IS NOT NULL AND "frequency_unit" IS NOT NULL)
  );

ALTER TABLE "encounter_prescriptions"
  ADD CONSTRAINT "encounter_prescriptions_duration_pair"
  CHECK (
    ("duration_value" IS NULL AND "duration_unit" IS NULL)
    OR ("duration_value" IS NOT NULL AND "duration_unit" IS NOT NULL)
  );

ALTER TABLE "encounter_prescriptions"
  ADD CONSTRAINT "encounter_prescriptions_dose_pair"
  CHECK (
    ("dose" IS NULL AND "dose_unit" IS NULL)
    OR ("dose" IS NOT NULL AND "dose_unit" IS NOT NULL)
  );

-- ⚠️ POSITIVE, NOT NON-NEGATIVE. A dose of zero, a course of zero days and a
--   quantity of zero are each a form that was started and abandoned, and each
--   would print on a prescription as an instruction.
ALTER TABLE "encounter_prescriptions"
  ADD CONSTRAINT "encounter_prescriptions_amounts_positive"
  CHECK (
    ("dose" IS NULL OR "dose" > 0)
    AND ("quantity" IS NULL OR "quantity" > 0)
    AND ("frequency" IS NULL OR "frequency" > 0)
    AND ("duration_value" IS NULL OR "duration_value" > 0)
  );

-- A course that ends before it starts is a typo the database can catch.
ALTER TABLE "encounter_prescriptions"
  ADD CONSTRAINT "encounter_prescriptions_dates_ordered"
  CHECK ("start_date" IS NULL OR "end_date" IS NULL OR "end_date" >= "start_date");

-- ---------------------------------------------------------------------------
-- A REFERRAL NAMES SOMEBODY.
--
-- A specialty ("see a cardiologist"), a named colleague inside the
-- organization, or a clinician outside it — all three are ordinary, and a row
-- naming none of them is a referral to nobody.
-- ---------------------------------------------------------------------------
ALTER TABLE "encounter_referrals"
  ADD CONSTRAINT "encounter_referrals_names_a_destination"
  CHECK (num_nonnulls("specialty_id", "doctor_profile_id", "external_name") >= 1);

-- ---------------------------------------------------------------------------
-- RLS — org + branch scoped, both loops, all eight tables.
--
-- ⚠️ `branch_id` IS NOT NULL ON ALL EIGHT, SO THE BRANCH POLICY IS ABSOLUTE —
--   the `branch_id IS NULL OR` half is dead code here, as it is for
--   `encounters` and for the invoice and inventory tables. A doctor scoped to
--   one site cannot read what another site prescribed, concluded or ordered
--   for a patient, even by guessing a primary key.
--
-- The canonical copy of these policies is `prisma/rls/enable-rls.sql`; this is
-- the stanza for the eight new tables, as the convention requires.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  org_branch_scoped text[] := ARRAY[
    'encounter_symptoms',
    'encounter_diagnoses',
    'encounter_procedures',
    'encounter_prescriptions',
    'encounter_investigations',
    'encounter_advice',
    'encounter_referrals',
    'encounter_attachments'
  ];
BEGIN
  FOREACH t IN ARRAY org_branch_scoped LOOP
    EXECUTE format('ALTER TABLE %I ENABLE   ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', t);

    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON %I
        USING      (organization_id = app_current_org())
        WITH CHECK (organization_id = app_current_org())
    $f$, t);

    EXECUTE format('DROP POLICY IF EXISTS branch_isolation ON %I', t);
    EXECUTE format($f$
      CREATE POLICY branch_isolation ON %I AS RESTRICTIVE
        USING      (branch_id IS NULL OR branch_id = ANY (app_branch_scope()))
        WITH CHECK (branch_id IS NULL OR branch_id = ANY (app_branch_scope()))
    $f$, t);
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- FIVE TABLES CITE A CLINICAL WORD THAT MAY BE A PLATFORM ROW.
--
-- ⚠️ THIS POLICY IS WHAT STANDS IN FOR THE COMPOSITE FK, WHICH IS IMPOSSIBLE
--   HERE — the same argument `template_visible` makes on `encounters`.
--   `clinical_master_items.organization_id` is nullable so that the platform
--   can ship a vocabulary every clinic sees; these rows' is NOT NULL, so a
--   composite reference would demand a word belonging to the clinic and refuse
--   every platform diagnosis on the platform.
--
--   Without this restriction a clinic could cite ANOTHER TENANT'S private word
--   and read its name and description back out of the join — which is a
--   competitor's clinical vocabulary, disclosed one selector at a time.
--
-- Written as a loop for the same reason the isolation policies are: five
-- identical stanzas differing only in a table name is five chances to fix a
-- bug in four places.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  cites_an_item text[] := ARRAY[
    'encounter_symptoms',
    'encounter_diagnoses',
    'encounter_procedures',
    'encounter_investigations',
    'encounter_advice'
  ];
BEGIN
  FOREACH t IN ARRAY cites_an_item LOOP
    EXECUTE format('DROP POLICY IF EXISTS item_visible ON %I', t);
    -- ⚠️ `item_id IS NULL OR …` because three of the five allow a typed entry
    --    with no coded word at all. On the two where the column is NOT NULL the
    --    left half is dead code, which is the same shape `designation_visible`
    --    has on `invitations`.
    EXECUTE format($f$
      CREATE POLICY item_visible ON %I AS RESTRICTIVE
        USING (item_id IS NULL OR EXISTS (
          SELECT 1 FROM clinical_master_items i
          WHERE i.id = %I.item_id
            AND (i.organization_id IS NULL OR i.organization_id = app_current_org())
        ))
        WITH CHECK (item_id IS NULL OR EXISTS (
          SELECT 1 FROM clinical_master_items i
          WHERE i.id = %I.item_id
            AND (i.organization_id IS NULL OR i.organization_id = app_current_org())
        ))
    $f$, t, t, t);
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- A PRESCRIPTION CITES A PRODUCT THAT MAY BE A PLATFORM ROW.
--
-- Exactly the shape `batches` has, and named the same. `NEXT_SESSION.md` item
-- 1 predicted this table would need it, and it does: without it a clinic
-- prescribes against another tenant's private product and reads its name,
-- strength and pack size back out of the join.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS product_visible ON encounter_prescriptions;
CREATE POLICY product_visible ON encounter_prescriptions AS RESTRICTIVE
  USING (EXISTS (
    SELECT 1 FROM products p
    WHERE p.id = encounter_prescriptions.product_id
      AND (p.organization_id IS NULL OR p.organization_id = app_current_org())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM products p
    WHERE p.id = encounter_prescriptions.product_id
      AND (p.organization_id IS NULL OR p.organization_id = app_current_org())
  ));

-- ---------------------------------------------------------------------------
-- A REFERRAL CITES A SPECIALTY THAT MAY BE A PLATFORM ROW.
--
-- Nullable — a referral to a named colleague or to somebody outside the
-- organization names no specialty at all — so NULL is permitted, as it is on
-- `clinical_episodes.primary_specialty_id`.
--
-- ⚠️ `doctor_profile_id` NEEDS NO POLICY, and that is not an omission. A doctor
--   profile is always org-scoped, so the composite FK CAN be drawn there and
--   is — which is the whole reason these `*_visible` policies exist only where
--   it cannot.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS specialty_visible ON encounter_referrals;
CREATE POLICY specialty_visible ON encounter_referrals AS RESTRICTIVE
  USING (specialty_id IS NULL OR EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = encounter_referrals.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ))
  WITH CHECK (specialty_id IS NULL OR EXISTS (
    SELECT 1 FROM specialties s
    WHERE s.id = encounter_referrals.specialty_id
      AND (s.organization_id IS NULL OR s.organization_id = app_current_org())
  ));

-- ---------------------------------------------------------------------------
-- Grants. Ordinary CRUD.
--
-- ⚠️ DELETE IS GRANTED AND IS THE ORDINARY WAY A ROW LEAVES A DRAFT — none of
--   these tables has a `deleted_at`, deliberately. A diagnosis the clinician
--   typed and then removed before signing is a correction to something that
--   was never a record; keeping a tombstone of it would make the chart's
--   history noisier without making it truer. Immutability begins at
--   FINALIZED, and it is `assertDraft` on the parent encounter that enforces
--   it — an amendment COPIES these rows onto a new encounter rather than
--   moving them, so both signed records stay whole.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  "encounter_symptoms",
  "encounter_diagnoses",
  "encounter_procedures",
  "encounter_prescriptions",
  "encounter_investigations",
  "encounter_advice",
  "encounter_referrals",
  "encounter_attachments"
TO rcln_app;
